### PR TITLE
#1001 Add a comment to fields used by shields.io

### PR DESCRIPTION
**Pull request by ericmoritz**
Fix for #1001. I guessed on the formatting of the comment. I can easily change it if needed.

### CODE REVIEW

**Comment by sgrif** [comment]
I'm not really sure that we need to specifically mark fields used by one client. We shouldn't be making any backwards incompatible changes to our API, as it is versioned and we know folks rely on it. (I'm not sure what specifically happened with #1001, I would guess that it never worked until it was fixed).

However, that issue has been open for a year so I'll defer to @carols10cents

**Comment by Turbo87** [comment]
@sgrif I believe https://github.com/rust-lang/crates.io/pull/787 is the PR that introduced the problem

**Comment by ericmoritz** [comment]
@sgrif I won't mind if we close this PR.  I was bored last night and grabbed a low hanging fruit.

**Comment by carols10cents** [comment]
> I'm not really sure that we need to specifically mark fields used by one client. 

[We already mark the routes that cargo uses](https://github.com/rust-lang/crates.io/blob/master/src/router.rs#L16-L19); this doesn't feel much different.

> We shouldn't be making any backwards incompatible changes to our API, as it is versioned and we know folks rely on it.

Mistakes happen, we haven't documented the requests that our frontend uses, and we have been known to say "oh we're the only one using this, we can change it" and then been wrong. 

I like this change. Thank you @ericmoritz !!

bors: r+

**Pull request merged**
