### PR TITLE
Add yank button to the web UI

### LINKED ISSUE #1659: Have a way to yank a crate from the UI
What needs to be done: This looks like a lot, but I tried to provide a lot of detail and examples to work from. The actual code changes shouldn't be very big.

- If the current user is an owner of the current crate, add a link or button in the sidebar with each version that says "yank" if the version is not yanked and "unyank" if the version is yanked. (Or is there a better place to put this control? I'm open to different UIs)
  - The HTML for the versions list in the sidebar is in https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/templates/crate/version.hbs#L195-L208
  - To tell if the current user is an owner, use the `isOwner` helper like the "Manage owners" section does here https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/templates/crate/version.hbs#L167-L173
  - Because we only show the latest 5 versions in the sidebar, the new link/button should be shown on the "All versions" page as well so any version can be yanked. The "All versions" page's HTML is here https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/templates/crate/versions.hbs

- The link/button should send a [`DELETE` request to `/api/v1/crates/[crate name]/[version num]/yank`](https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/src/router.rs#L23) for yanking and a [`PUT` request to `/api/v1/crates/[crate name]/[version num]/unyank`](https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/src/router.rs#L23) for unyanking.
  - A similar link/button is the "Remove" button for removing an owner https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/templates/crate/owners.hbs#L67
  - Which calls the ember `removeOwner` controller function: https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/controllers/crate/owners.js#L34-L49
  - Which calls the ember crate model `removeOwner` function: https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/models/crate.js#L48-L50
  - Which calls the ember crate adapter `removeOwner` function: https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/adapters/crate.js#L16-L22
  - I'm not actually sure how idiomatic Ember this example is; if this example isn't good, feel free to do whatever the normal Ember way of doing this would be.
  - There should be an indication to the user that the request is being sent and then that the request has completed either successfully or with an error. You should be able to yank and unyank the same version repeatedly without reloading the full page.

- The ember tests should assert that the UI behaves as expected. This commit has an example of adding an ember test for the "remove owner" functionality: https://github.com/rust-lang/crates.io/commit/f524472a5f920958f43a7d6ae79bea925ab66969

- There should be a test in the Rust code that yank and unyank can be performed by `MockCookieUser`s as well as `MockTokenUser`s.
  - Implement `yank` and `unyank` helper methods on [like they are on `MockTokenUser`](https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/src/tests/krate.rs#L63-L79)
  - Duplicate [this test](https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/src/tests/krate.rs#L1450-L1486) and instead of calling `yank` and `unyank` on the `MockTokenUser`, call them on the `MockCookieUser`.
  - The owners tests are good examples of using a `MockCookieUser`. https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/src/tests/owners.rs

### PR DESCRIPTION
**Pull request by thiagoarrais**
Trying to fix #1659

This adds a yank/unyank button to the crate and versions pages.

By the way, I'm learning Ember and the crates.io codebase for this one. Please review accordingly. I'm assuming that there is a lot of things out of place. Just let me know where everything should go.

**Some questions:**

1. I've based this button on the edit email button from the account page, but had to make it smaller because of lack of screen real estate. Is that ok? If so, should this live in the component's `yank-button.module.css` or should I create a `.smaller` entry in `shared/buttons.module.css`?

2. Added `yank-button.js` just to specify an empty tag name that in turn makes Ember avoid generating an enclosing `div` that breaks styling. Is there a cleaner way to do that?

### CODE REVIEW

**Comment by thiagoarrais** [comment]
Tagging @carols10cents (original issue author), @locks (original issue assignee) and @sgrif (pull request assignee) for review.

Folks, the crates.io codebase is very nice to work with. Special thanks for the folks that wrote the contributing guide. Just let me know if you need anything else.

**Comment by jtgeibel** [comment]
Hey @thiagoarrais thanks for the PR! Several volunteers on the team are on vacation right now, so it may take a while to get this merged, but I've tried this out locally and have a few initial suggestions.

On the page showing all versions of a crate, we can probably get rid of the green arrow. This is a small click target (right next to the new buttons) and links to the same page as the version text on the left.

image

On the crate pages, I'm not sure about having this shown for each version:

image

I think instead of showing the button here, we could show this at the top of the version-specific pages (so `crates/name/0.1.0` but not `/crates/name`). Maybe next to the follow/unfollow button. Then a user can go to the version page if they want to yank several versions at once, or to a specific version to modify it. I don't think it's necessary to add the buttons to the bullet point list here.

**Comment by thiagoarrais** [comment]
Thanks for the review, @jtgeibel!

Regarding the idea of moving the button to the page header. This is what I came up with so far:

Captura de tela de 2020-07-29 13-46-33

I really like this idea. I've chose to place the yank button next to the version number. I think this makes it clearer that this is an action specific to that version, as opposed to an overall crate action (like the follow button). But I haven't got a ton of design skills and the button now seems a little out of place. Any ideas for making this better?

By the way, I've also removed the green arrow from the owner view.

**Comment by thiagoarrais** [comment]
Here are some options for the positioning of the yank button. This PR uses the first option for the time being, but it still needs some work. I'm also open to other options, of course. What do you folks think?

## Option A: Small button next to the version number

option-1-next-to-version

This is the current approach written into this PR. I think it makes clear(er) that the action refers to the specific version. We may assume that crate authors are already used to yanking versions (and not full-blown crates), but I think being more specific here avoids some confusion.

That said, this needs some layouting work. I can't pinpoint exactly why, but the button as is looks a little out of place to me.

## Option B: Large button next to the follow button

option-3-next-to-follow

This one avoids the positioning problem, but it may be confusing for crate authors. It may look like the yank action refers to the crate itself, not the specific version. This is aggravated by the presence of the follow button, that _does trigger_ an action referring to the crate, not the version. Which brings us to...

## Option C: Large button replacing the follow button

option-2-replacing-follow

This is a variant on the previous approach. In my opinion, it may also be confusing. But at least here we have fewer buttons polluting the interface. That said though, maybe the yank button gets "invisible" because of crate owners being used to that area of the screen belonging to the follow button (both prior this PR and when viewing thirdy party crates).

**Pull request merged**
