### PR TITLE
Leverage readme_path to support relative paths from readme's not at root

### PR DESCRIPTION
**Pull request by nipunn1313**
Added unit tests to confirm things work.
Manually tested end to end and confirmed that the rendered
page has a properly working relative link as long as the Cargo.toml
is in the root of the repo.

We'll need to update cargo as mentioned in #3484 in order to
support Cargo.toml that aren't in the root of the repo

### CODE REVIEW

**Comment by nipunn1313** [comment]
Here's me doing the best I can to show a screenshot of my manual test.
README is not in root (it's in `docs/README.md`). It has a relative link to `./Otherfile.md` (also in docs)
Prior to this diff, the rendered MD->html would have a bad link. Now it looks good!
image

**Comment by nipunn1313** [comment]
(rebased on master - to handle merge conflicts)

**Review by Turbo87 — APPROVED** [review]
LGTM, thanks! 👍

**Pull request merged**
