### PR TITLE
Adding categories related to Aerospace

### LINKED ISSUE #4105: Adding more categories
Hello :wave:
**Aerospace categories**
I would like to ask about adding more categories regarding `aerospace` in general (from protocol implementations, sdks, apis, simulations, etc).
This issue is more of a discussion on what categories could be added.

**Why?**
I am aware that there are a few categories like `simulations`, `science` & `science::robotics`, etc, however, I would like to have categories specifically for aerospace in order to collect and showcase them in https://areweinspaceyet.org/ automatically.

I'm planning a new version of the website which won't require manually entering crates and instead will build the list of crates for a specific categories and maybe keywords.

**Other options:**
It is possible to use a specific keyword e.g. `#aerorust` that will mark a crate which wants to end up in this list, however, it will still require some categories to be whitelisted and prevent misplaced crates.

I believe that the categories in crates.io could be used by other communities, lists (awesome-lists) and websites like:
- https://www.arewewebyet.org/
- https://areweasyncyet.rs/
- http://www.arewelearningyet.com/
- etc.

### PR DESCRIPTION
**Pull request by elpiel**
Resolves #4105

I've also added the category `Software-defined radio`.
Here are 2 crates that are in this category:

- https://github.com/rsadsb/adsb_deku
- https://github.com/FutureSDR/FutureSDR

I can remove the `SDR` from this PR if it's necessary to discuss it first at a meeting @Turbo87.

CC @wcampbell0x2a @bastibl @MoralCode

### CODE REVIEW

**Comment by Turbo87** [comment]
> I can remove the `SDR` from this PR if it's necessary to discuss it first at a meeting @Turbo87.

yeah, let's move that out of the PR to unblock the others. I'm not sure yet about a top-level SDR category or whether we should rather move it into "Science" for example. It seems like a very specific one and I'm wondering if there is a way to generalize it a bit more.

**Comment by elpiel** [comment]
> > I can remove the `SDR` from this PR if it's necessary to discuss it first at a meeting @Turbo87.
> 
> yeah, let's move that out of the PR to unblock the others. I'm not sure yet about a top-level SDR category or whether we should rather move it into "Science" for example. It seems like a very specific one and I'm wondering if there is a way to generalize it a bit more.

Ok, it's removed. Thank you!

**Comment by Turbo87** [comment]
Thanks! :)

@bors r+

**Comment by elpiel** [comment]
> Thanks! :)
> 
> @bors r+

No, thank you!
Happy 2022 :yum:

**Comment by Turbo87** [comment]
https://crates.io/categories/aerospace

have fun 😉

**Comment by MoralCode** [comment]
> I'm not sure yet about a top-level SDR category or whether we should rather move it into "Science" for example. It seems like a very specific one and I'm wondering if there is a way to generalize it a bit more.

is there already a `Radio` or `RF` or `Electromagnetic Spectrum` type categories? it seems like those might be some appropriate categories to put SDR underneath (in order of increasing generality)

**Comment by Turbo87** [comment]
@MoralCode the current set of categories is defined at https://github.com/elpiel/crates.io/blob/master/src/boot/categories.toml

**Comment by MoralCode** [comment]
ah yeah I saw that, what I meant was those could be some possible names for generalizations of an SDR category if they don't already exist

**Comment by elpiel** [comment]
> ah yeah I saw that, what I meant was those could be some possible names for generalizations of an SDR category if they don't already exist

Maybe start a new issues to add more categories if you have an idea how they can look?
I'm also not entirely sure about the separation of the 2 categories - Unnamed aerial vehicles & drones so I'm opened for ideas.

**Pull request merged**
