### PR TITLE
Support dark mode

### PR DESCRIPTION
**Pull request by wyhaya**
Preview:

https://user-images.githubusercontent.com/23690145/117098095-0e3a3380-ada0-11eb-8414-aad756be25af.mp4

Related: #3489

### CODE REVIEW

**Comment by Turbo87** [comment]
unfortunately such large scale changes to the design are currently considered problematic by the webpresence subteam 😞

**Comment by anahata0108** [comment]
Can you explain what's problematic about this change? It's a big accessibility win. I never use crates.io because it doesn't support dark mode. What's needed to move this forward?

**Comment by Turbo87** [comment]
we've discussed this PR in the weekly crates.io team meeting today and we're generally not against implementing a dark mode and we would like to move this forward. we still need to figure out a few details though and we would like to hide this behind some kind of feature flag for now. once we have a more detailed plan on how we want to approach this I'll let you know.

**Comment by silvioprog** [comment]
>  The latest upstream changes (presumably #3681) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#conflicts).

Ping @wyhaya

**Comment by Patrick-Poitras** [comment]
@Turbo87 With #4368 being merged in, is this PR still blocked from proceeding, or what is the status on the implementation of dark mode?

**Comment by Turbo87** [comment]
the short version is: we're working on it 😉

**Comment by videah** [comment]
Is there any progress being made towards making this a reality? I'm finding that it isn't possible for me to use crates.io for long periods of time without getting searing headaches 🥲

**Comment by carols10cents** [comment]
If there was any progress, it would be posted to this issue. We'd love if you sent in PRs!

**Comment by r00ster91** [comment]
And as always, [Dark Reader](https://darkreader.org/).

**Comment by fenhl** [comment]
Looks like deleting the target branch automatically closed this, so it will have to be reopened against `main`.

**Comment by jdno** [comment]
Huh, that was definitely not supposed to happen. The target branch should've been updated without the pull request getting closed. 🤨

But I also can't find the fork from which the PR was created, so maybe that's what why this PR got closed instead of updated.

**Comment by fenhl** [comment]
Hopefully we can avoid losing track of this. @wyhaya would you be willing to recreate the branch?

**Comment by wyhaya** [comment]
Hi @fenhl 

I inadvertently deleted the fork of this repository, and unfortunately I can't recreate the branch. The best I can think of is to copy the code line by line from this PR.

This PR submission is more than two years old and is probably no longer appropriate for crates.io. The CSS code in it is poorly written and I think a rewrite might be a good idea.

**Comment by msrd0** [comment]
It is still possible to recover the code using the github cli:

```
gh pr checkout 3585

**Pull request closed without merging**
