### PR TITLE
Update development environment setup info

### PR DESCRIPTION
**Pull request by camelid**
You can't run the app without installing the Ember CLI.

### CODE REVIEW

**Comment by camelid** [comment]
The Ember CLI *does* seem to be installed when you run `npm install`, but it isn't in your path. Is it correct to instruct people to install a global copy of the CLI?

**Comment by locks** [comment]
@camelid what the globally installed ember-cli is doing is essentially proxying to the project's ember-cli. You should be using the package.json scripts to run the app and the various tasks, so the global installation shouldn't be required.
How did you stumble into the problem?

**Comment by camelid** [comment]
Hmm, I followed the contributing guide and ran `npm install`, but then when I ran `npm run start:live`, I got this:

```
> cargo@0.0.0 start:live /Users/me/crates.io
> ./script/ember.sh serve --proxy https://crates.io

./script/ember.sh: line 12: ember: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! cargo@0.0.0 start:live: `./script/ember.sh serve --proxy https://crates.io`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the cargo@0.0.0 start:live script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2020-09-08T22_34_45_134Z-debug.log
```

**Comment by camelid** [comment]
Running `npm install -g ember-cli` made it work. Also changing the `ember.sh` script to use `../node_modules/ember-cli/bin/ember` worked.

**Pull request closed without merging**
