### PR TITLE
Replace `ember-ajax` with `ember-fetch`

### PR DESCRIPTION
**Pull request by tchak**
This will path the way to eventually remove jQuery :)

### CODE REVIEW

**Comment by Turbo87** [comment]
@tchak do the error messages change in any way after this?

**Comment by carols10cents** [comment]
We tried switching to ember-fetch a while ago and had [a problem](https://github.com/rust-lang/crates.io/issues/820)-- i don't know enough about what we were doing then, what might be different now, and what the cause of that problem was to know whether this will still be a problem :-/

**Comment by tchak** [comment]
@carols10cents thanks for pointing it out. I will investigate and report!

**Comment by tchak** [comment]
@Turbo87 it should not :) I will do a serie of manual tests and check.

**Comment by Turbo87** [comment]
@tchak @tylerturdenpants I've rebased this on `master` now

**Comment by Turbo87** [comment]
Awesome, thanks for the verification!

**Pull request merged**
