### PR TITLE
Sort optional dependencies last

### LINKED ISSUE #527: Sort optional dependencies last
e.g. https://crates.io/crates/image has multiple dependencies, some of which are optional. But from the layout it's not easy to see which ones are optional. Sorting optional dependencies separately would IMHO make it clearer.

### PR DESCRIPTION
**Pull request by Eh2406**
fixes #527

### CODE REVIEW

**Comment by carols10cents** [comment]
Just curious, why does the `ORDER BY` include `crate_id` too?

**Comment by Eh2406** [comment]
No really good reason. While I am removing arbitrary ordering, may as well do it hear. Alphabetical is easy and better than arbitrary. But I am not strongly wedded to it.

**Comment by carols10cents** [comment]
Yeah, I think alphabetical by name would make more sense. Mind making that change? Thanks!

**Comment by Eh2406** [comment]
I was assuming order by `crate_id` and order by name would be similar. I will go look at the schema to determine if `crates` or `dependencies` has a name. Then to make the switch.

**Comment by Eh2406** [comment]
switched and rebased.

**Comment by carols10cents** [comment]
Awesome, thank you!!! ☃️

**Pull request merged**
