### PR TITLE
Revert `base64` dependency upgrade

### PR DESCRIPTION
**Pull request by Turbo87**
This should temporarily resolve https://github.com/rust-lang/crates.io/issues/5646 until we figure out what exactly went wrong and why the background worker still seems to be running correctly despite the Sentry error reports.

### CODE REVIEW

**Comment by paolobarbolini** [comment]
It probably has to do with base64 0.20 requiring correct padding by default when decoding

**Comment by Turbo87** [comment]
yeah, that's possible. I wish their changelog was a bit more explicit about changing the default behavior of their main API interface... 😩

**Comment by paolobarbolini** [comment]
yeah. BTW considering all of the changes that had to be done to move to 0.20 you too might be interested in https://github.com/marshallpierce/rust-base64/issues/205

**Comment by Turbo87** [comment]
oh dear... thanks for the link 🙈

**Comment by Turbo87** [comment]
> why the background worker still seems to be running correctly despite the Sentry error reports.

I figured it out... I did not notice yesterday that the Sentry issues were only for the staging environment, but in production everything was working fine. 😅

**Pull request merged**
