### PR TITLE
cargo fmt

### LINKED ISSUE #574: Run rustfmt on the whole codebase and send in the changes
I know I've been adding code to crates.io that isn't necessarily idiomatic rust formatting and I'd like to stop thinking about it and just run rustfmt :) There's probably a lot of code that isn't formatted the way rustfmt would do it though!!

This bug involves:

- Installing [rustfmt](https://github.com/rust-lang-nursery/rustfmt) on your machine if you haven't yet, using the "Quick start" instructions in their README
- Run `cargo fmt` in your crates.io checkout
- Send in a PR for whatever it recommends changing
- Fix the tests if any fail (hopefully they shouldn't!)

### PR DESCRIPTION
**Pull request by vignesh-sankaran**
Fixes #574. Ran rustfmt over the codebase, went smoothly except for this line here (https://github.com/rust-lang/crates.io/blob/master/src/db.rs#L66), but I think that there isn't much we're going to be able to do about that

### CODE REVIEW

**Comment by elliotekj** [comment]
Hey @vignesh-sankaran :)

I have a few suggestions for this:

1. A rustfmt config file should probably be added to the codebase as part of this PR for consistency going forward. The RFC rustfmt config [was suggested](https://github.com/rust-lang/crates.io/pull/581#issuecomment-306519550) by @steveklabnik — was that the one you used?

2. Rustfmt has [a skip attribute](https://github.com/rust-lang-nursery/rustfmt/blob/master/tests/target/skip.rs) which should let us work around the long function name from the OpenSSL crate.

3. Again for consistency going forward, [the Travis config](https://github.com/rust-lang/crates.io/blob/master/.travis.yml) should probably be updated as part of this PR to fail if code isn't formatted correctly: https://github.com/rust-lang-nursery/rustfmt#checking-style-on-a-ci-server

Just my suggestions — best to wait and see what @carols10cents has to say before acting on anything.

Cheers!

**Comment by carols10cents** [comment]
Yup, I agree with @elliotekj's suggestions-- do you mind making those changes @vignesh-sankaran? Please let me know if you have any questions!

**Comment by vignesh-sankaran** [comment]
In response @elliotekj, I just used rustfmt with overwrite, I'll redo the rustfmt pass with the config file. Thanks for the tip regarding the skip attribute, I'll add that in too. 

No problems @carols10cents, looks like I'll fix up #575 in the process as well.

**Comment by carols10cents** [comment]
Thank you so much!! I've merged this in, and I decided to move the documentation to CONTRIBUTING.md and I added some notes about jslint and clippy too.

I also was able to get the max_width down to 118, but then I discovered the [error_on_line_overflow](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#error_on_line_overflow) setting, which I think does about what we want here, since the line with the super long SSL function can't be fixed [or ignored](https://github.com/rust-lang-nursery/rustfmt/issues/1298).

I also changed the default write mode to Overwrite, since that's what I usually want when I run locally.

Thank you!! I'm so excited to be able to stop agonizing over the formatting!!!

**Comment by vignesh-sankaran** [comment]
No worries @carols10cents, good to hear you'll be stressing less over code formatting :)

**Pull request merged**
