### PR TITLE
Sync doc sections

### PR DESCRIPTION
**Pull request by matklad**
See https://github.com/rust-lang/cargo/pull/3865

### CODE REVIEW

**Comment by carols10cents** [comment]
Thank you!!!! I don't like how this is split across repos.... someday we'll fix it...

**Comment by matklad** [comment]
@carols10cents should something else be done to upgrade the crates.io site? It still points to the old machine readable output section, which now gives 404. 

> I don't like how this is split across repos.....

I also wonder why `doc.crates.io` is an entirely separate machine...

**Comment by steveklabnik** [comment]
> I also wonder why doc.crates.io is an entirely separate machine...

It's just github pages, rather than being a dynamic site. That's all it
really needs anyway.

**Comment by carols10cents** [comment]
@matklad I need to deploy. Working on it right now, I had an issue.

@steveklabnik the problem is that the docs menu on the dynamic crates.io pages needs to match the menu on github pages and that is 💩

**Comment by carols10cents** [comment]
@matklad deployed! Sorry for the delay! ❤️

**Comment by steveklabnik** [comment]
Oh yeah, it's certainly less than ideal.

**Comment by carols10cents** [comment]
Ok. Redeployed. 🤞🤞🤞🤞🍀🍀🍀🍀🍀

**Comment by carols10cents** [comment]
Ok for real real real this is actually deployed and i dont think i'll have to roll this one back. Famous last words, I know :)

**Pull request merged**
