### PR TITLE
Link to getting started guide when search result is empty

### LINKED ISSUE #738: Link to Getting Started documentation for empty search result
When searching for a create that does not exist yet, users get presented with a relatively empty page "Displaying 0-0 of 0 total results". I think it would be great to link to the Getting Started document and suggest starting your own crate. Alternatively we could offer some spell suggestions but that might be a bit too much.

### PR DESCRIPTION
**Pull request by dignati**
Resolves #738. I'm happy to make any changes necessary so feel free to suggest wording, styling and code.

### CODE REVIEW

**Comment by dignati** [comment]
Of course feel free to close this if it's not something you want added. I basically just wanted to try and play around with the crates.io source code.

**Comment by carols10cents** [comment]
Oh I do want this, I just haven't had much time lately. I hope to look at this today! Thank you!!

**Comment by carols10cents** [comment]
Thank you so much for your patience-- this is great!!!

**Comment by dignati** [comment]
Great, glad to help :)

**Pull request merged**
