### PR TITLE
Enable FastBoot (again)

### PR DESCRIPTION
**Pull request by kzys**
Compared to #1715, this branch

- Runs 2 processes from Procfile, instead of using node-foreman.
- Makes the number of child processes `cluster` creates configurable, and the default value is one.

The memory consumption is at most ~197MB on my Heroku environment. Of course the environment is having only a few requests from my browser though. Would it be acceptable?

Untitled

### CODE REVIEW

**Comment by kzys** [comment]
Untitled 2

**Comment by kzys** [comment]
Okay. The last commit (ebff9feb87d296e8741f398c897bca0fa7e2c46b) changed the memory consumption a lot.

Untitled

**Comment by kzys** [comment]
I will update the branch once #1853 got merged, since this branch probably will conflict with that.

**Comment by jtgeibel** [comment]
I think it would be beneficial to break out enabling FastBoot (in the Procfile, nginx configuration, and app-initialized file handling) into a separate PR.  That way we could land the other fixes in this PR ASAP, and then have a smaller PR that is easier to enable and revert if necessary.

It would be ideal if we could dynamically enable/disable FastBoot via an environment variable, similar to how hyper can be selected at boot time with the [USE_HYPER](https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/src/bin/server.rs#L60) environment variable.  However, that seems tricky in this case, because we would need to dynamically configure nginx before starting it.

So I don't think we need to try to make this a dynamic configuation at this time, but I think it would make sense to break out the diff that actually enables FastBoot into its own PR and land the rest of these changes now.

**Comment by kzys** [comment]
I think it is possible to implement the dynamic configuration, since the Nginx Buildpack is using ERB for templating.

Anyway, I've created #1886 which contains Fastboot-related changes, except for actually enabling Fastboot. Please take a look!

**Comment by kzys** [comment]
Since we already have #1811 for tracking. I'm going to close this PR. We may have discussions on the tracking PR.

**Pull request closed without merging**
