### PR TITLE
breaking long words in the crates list

### LINKED ISSUE #451: Frontpage Columns Messed Up
On the front page of https://crates.io, the really long version number messes up the formatting: 

screenshot from 2016-10-03 20-46-34

This is on Linux (Ubuntu 16.04 x86-64) with both Chrome (Version 50.0.2661.86 (64-bit)) and Firefox (Mozilla Firefox 51.0a2)

### PR DESCRIPTION
**Pull request by rjgoldsborough**
fixes #451 

(I could no longer see that crate so I just made up a very long version number)

screen shot 2016-10-06 at 10 21 53 am

### CODE REVIEW

**Comment by steveklabnik** [comment]
I like it. @carols10cents / @alexcrichton ?

**Comment by alexcrichton** [comment]
Is there a CSS way to truncate a version? I'd personally prefer  something like `very-long-v...` so everything always fit on one line

**Comment by rjgoldsborough** [comment]
Yeah, there is https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow which I tried first, but that needs to be on the anchor tag I believe and since it's a flex child, it doesn't have a sense of width and thus can't really know what is overflowing and what to clip. That's why I had to set that property up the tree.

I can keep banging on it if that's definitely preferred.

**Comment by alexcrichton** [comment]
Yeah perhaps we can tweak the markup here to take advantage of that?

**Comment by rjgoldsborough** [comment]
Sure, I'll try that

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
