### PR TITLE
Add Cargo documentation dropdown to the top nav bar (better spacing this time)

### PR DESCRIPTION
**Pull request by birkenfeld**
Ok, next try. See screenshot...

2016-03-01-071018_1920x1080_scrot

### CODE REVIEW

**Comment by alexcrichton** [comment]
Maybe there's just not enough room for this? It still looks kinda scruched up to me:

**Comment by birkenfeld** [comment]
That's not optimal, yes. Could shorten it to "Docs", but that would have been matched with doc.crates.io.

**Comment by alexcrichton** [comment]
I'd be fine with that yeah

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
