### PR TITLE
Issue #574 - Initial run of rustfmt on the whole codebase.

### PR DESCRIPTION
**Pull request by Insomgla**
Still 2 errors that rustfmt is not able to solve on its own.

I'll fix one by hand, and skip the other one since it's not possible to fix it automatically (it involves renaming a method of the OpenSSL library).

### CODE REVIEW

**Comment by Insomgla** [comment]
Wierd, by running `cargo fmt` again, it seems that some files didn't get formatted correctly at first.

**Comment by Insomgla** [comment]
There's an issue with `rustfmt`, the skip attribute doesn't seem to work properly. It will still yell at me for a method, the name of which is too long. I'll open an issue on rustfmt's repository. Maybe I use it badly, though.

**Comment by carols10cents** [comment]
@Insomgla let me know if you need help figuring out the rustfmt issue! Have you filed an issue with rustfmt yet? 

I think I'm going to merge the `?` change first, since it should be easier to run rustfmt again, hope you don't mind!!

**Comment by Insomgla** [comment]
That would be a smart choice indeed :p and I opened an issue, yes.

**Comment by carols10cents** [comment]
Ah cool, found it: https://github.com/rust-lang-nursery/rustfmt/issues/1345

**Comment by carols10cents** [comment]
While not ideal, wdyt about setting rustfmt's max width to 138 (the length of [this line](https://github.com/rust-lang/crates.io/blob/master/src/db.rs#L61))? That would let us move forward, and it's not much higher than the default of 100.

**Comment by carols10cents** [comment]
Hi @Insomgla, since this has gotten a bit out of date and both crates.io and rust-fmt have changed in the meantime, I'm going to give this a close. I'm still interested in having rust-fmt enabled, please feel free to submit a new PR in the future and I won't let it sit so long next time, I promise! :)

**Comment by steveklabnik** [comment]
Also, using https://github.com/rust-lang-nursery/rustfmt/blob/master/rfc-rustfmt.toml would be a good idea 💯

**Pull request closed without merging**
