### PR TITLE
Move frontend dependencies to devDependencies

### PR DESCRIPTION
**Pull request by jtgeibel**
The only remaining dependencies are for experimental fastboot support.

r? @Turbo87

### CODE REVIEW

**Comment by jtgeibel** [comment]
Screwed up commas in JSON twice now with this PR :crossed_fingers:

**Comment by jtgeibel** [comment]
As expected, moving these two packages doesn't really have a noticeable reduction in slug size.

**Comment by Turbo87** [comment]
I've started using this convention where all packages that are imported via ember-auto-import are put into `dependencies` to signal that they are technically not build-time dependencies. The way the build currently works they will still be build-time dependencies and not imported from `node_modules` at runtime, but that might change in the future.

> As expected, moving these two packages doesn't really have a noticeable reduction in slug size.

If it's not noticeable, if the change really worth it? 😅

**Comment by jtgeibel** [comment]
> If it's not noticeable, is the change really worth it?

At this time, I don't think so, so closing this PR.

> I've started using this convention where all packages that are imported via ember-auto-import are put into dependencies to signal that they are technically not build-time dependencies.

I'm interested in hearing more about this. At first glance, I don't see a difference in how `pretty-bytes` and `copy-text-to-clipboard` are used compared to other dependencies, but I'm probably missing something.

**Comment by Turbo87** [comment]
> I'm interested in hearing more about this. At first glance, I don't see a difference in how `pretty-bytes` and `copy-text-to-clipboard` are used compared to other dependencies, but I'm probably missing something.

the difference is that they are regular JS modules that are imported in the `app` folder, vs. using import paths that are supplied by Ember addons. but as I said, both should work fine, I've just used it as a convention in several projects so far :)

**Pull request closed without merging**
