### PR TITLE
Update diesel and diesel_migrations to version 1.2

### PR DESCRIPTION
**Pull request by Andy-Bell**
Updates these crates (and linked crates such as diesel_derive) to version 1.2 from version 1.1

### CODE REVIEW

**Comment by jtgeibel** [comment]
Thanks for the contribution!  You may also want to bump the diesel version in the `cargo install` line in `.travis.yml`.

**Comment by Andy-Bell** [comment]
Good point, have now updated that 👍

**Comment by jtgeibel** [comment]
Thanks for the update!  I've thought of a few more things.

We still have `0.16.0` in `.diesel_version` and this is what Heroku will use to run migrations when deploying.

It also looks like we have a typo in `docs/CONTRIBUTING.md` where we suggest version `>= 1.11.0` on line 150.

**Comment by Andy-Bell** [comment]
Updated those as well, thanks

**Comment by sgrif** [comment]
bors: r+

**Pull request merged**
