### PR TITLE
Convert a few components to template-only components

### PR DESCRIPTION
**Pull request by Turbo87**
r? @locks

### CODE REVIEW

**Comment by locks** [comment]
@Turbo87 can you check the Percy failure? `user-link` might need a tweak to preserve the spacing.

**Comment by Turbo87** [comment]
looks like I forgot a `...attributes`. should be fixed now.

the GitHub Actions "Backend (beta)"  job currently seems flaky for unrelated reasons.

**Comment by locks** [comment]
We're getting some failures I haven't investigated 🤔

**Comment by Turbo87** [comment]
@locks sorry, my fault. should be fixed now!

**Pull request merged**
