### PR TITLE
Add Dockerfiles and docker-compose file

### LINKED ISSUE #943: Dockerising development environment
Thought it'd be nice if we had a Docker container for managing the development environment rather than needing to set things up based on the host OS.

### PR DESCRIPTION
**Pull request by anthonynguyen**
This PR resolves #943.

I'm pretty sure I've made it so running `docker-compose up` will just work, but someone else will definitely have to verify.

I also wanted to spawn a Minio (or something similar) service to replace S3, but currently the S3 host isn't configurable so I might do all that in another PR.

### CODE REVIEW

**Comment by anthonynguyen** [comment]
Not sure why the one build is failing

**Comment by carols10cents** [comment]
@anthonynguyen I don't know why that failed either, it happens sometimes and I haven't figured it out. I restarted that job!

**Comment by carols10cents** [comment]
Looks good at a glance, I don't really use docker but I'm fine merging this and fixing anything if someone finds it's not working!

Thank you for this!! ❤️ 

bors: r+

**Comment by carols10cents** [comment]
bors: r+

**Pull request merged**
