### PR TITLE
Add Gitlab CI badge support.

### LINKED ISSUE #537: Support Gitlab badges
In addition to AppVeyor and Travis it'd be good to support Gitlab CI badges. I use AppVeyor for Windows, but use Gitlab CI for Linux build testing and I'd like to have both badges shown for my crate. Documentation for their badges is here: https://gitlab.us/help/user/project/pipelines/settings.md#badges

I'll try to whip up a PR for this in the next few days if I have time, I'm mostly posting this issue to see if a PR for this would be accepted before I spend my time on it.

### PR DESCRIPTION
**Pull request by Susurrus**
Resolves #537.

I tested this code by modifying `app/mirage/fixtures/search.js` with data from my `gattii` crate, which has Gitlab CI configured. None of the existing projects in this file have gitlab CI, so should I add my `gattii` crate information to this file? If so, is there an easy way to grab this info (maybe a REST call to the real crates.io)?

I know there are badge tests in `src/tests/badge.rs`, but it's all one big complicated test. Should I try to integrate a gitlab badge into that existing test or create a new one? I'm not really certain what to do here that would be best so some guidance here would be helpful.

### CODE REVIEW

**Comment by Susurrus** [comment]
CCing @carols10cents Since you commented on the original issue (#537)

**Comment by carols10cents** [comment]
> None of the existing projects in this file have gitlab CI, so should I add my gattii crate information to this file? 

It's not actually be necessary for the badge to really load-- The ember tests are just looking at the generated markup. So it should be fine to add to the `badges` data for the external-mixin crate fixture, which is the first row, so then you can just add another assertion [in with the other ones](https://github.com/rust-lang/crates.io/blob/master/tests/acceptance/search-test.js#L27-L28) on the same row.

> I know there are badge tests in src/tests/badge.rs, but it's all one big complicated test. Should I try to integrate a gitlab badge into that existing test or create a new one? I'm not really certain what to do here that would be best so some guidance here would be helpful.

In general the Rust tests are a lot longer than I would write, personally, but so far they seem to be working out okay-- there's a lot of setup and stuff that makes longer tests make more sense than in other circumstances. So go ahead and add gitlab in the same test as the other badges!

The code looks great so far! The only thing is it looks like you took out the deny warnings in  src/bin/delete-crate.rs ? When you add the tests, could you take that change out please? 

Thank you so much!!!! ❤️ ❤️ ❤️

**Comment by Susurrus** [comment]
So there's one more change I need to fix, but it's blocking on Gitlab coming back up, but I'll take care of that tomorrow.

**Comment by Susurrus** [comment]
So Gitlab's back so everything should be good now.

One thing I should comment on is that the badge link URL points to the /pipelines page for the repo, not to the commit list for the set branch as Gitlab suggests in their Markdown badge examples. This keeps it's functionality consistent with the other badges, where they all link as directly as possible to the CI results page.

**Comment by Susurrus** [comment]
I think we're all good with this one. I also submitted rust-lang/cargo#3632, which should round out the documentation at least in the codebase itself.

**Comment by carols10cents** [comment]
Looks great!!!! Thank you!!! ❤️

**Comment by Susurrus** [comment]
Awesome, thanks @carols10cents. I'm not familiar with the deployment process for crates.io and if it eides the same trains as Rust. So you know when this might be deployed and usable?

**Comment by carols10cents** [comment]
@alexcrichton manages deployment, I'm not sure how often.

**Comment by alexcrichton** [comment]
Ah yes this should be deployed now!

**Comment by Susurrus** [comment]
@alexcrichton When is deployment done? Is it as soon as a new commit is merged in by bors? This would be helpful to document somewhere I think.

**Comment by alexcrichton** [comment]
When I hit a button, and yes lots of things would be useful if they were documented!

**Comment by Susurrus** [comment]
Well I'd be happy to help! Let me know if you think I could help here.

**Comment by chris-morgan** [comment]
There’s a spelling mistake in all of this: it’s GitLab, not Gitlab. (Just like GitHub is GitHub, not Github.)

Yes, this definitely needs to be fixed.

**Comment by Susurrus** [comment]
@chris-morgan I'll submit a new PR for this (as this has already been merged) otherwise if you want to file a new issue we can track that work there.

**Comment by Susurrus** [comment]
@chris-morgan see rust-lang/cargo#3669 and #547.

**Pull request merged**
