### PR TITLE
Refactor login code to use `postMessage()` instead of polling loop

### PR DESCRIPTION
**Pull request by Turbo87**
I got nerd-sniped by the following comment in the codebase:

> For the life of me I cannot figure out how to do this other than polling

This PR simplifies the implementation and now uses the recommended way to communicate between parent and child window: `window.postMessage()`

see https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage for more information

r? @jtgeibel

### CODE REVIEW

**Comment by Turbo87** [comment]
FYI I'm currently deploying this to the staging environment so that we can test it out before merging

**Comment by jtgeibel** [comment]
Glad to see this implemented in the right way! LGTM, and works fine on staging.

@bors r+

**Pull request merged**
