### PR TITLE
Make search field require input before searching

### PR DESCRIPTION
**Pull request by DirkyJerky**
If you search for nothing (click the field and hit enter), it responds with zero results.
Might as well disable it from doing so.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like there's a travis error though?

**Comment by DirkyJerky** [comment]
@alexcrichton Fixed.

**Comment by DirkyJerky** [comment]
@alexcrichton Fixed.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
