### PR TITLE
Retina Icons

### PR DESCRIPTION
**Pull request by octplane**
- all retina icons in public/assets
- added source in assets/: Sketch file and checker source
- fixed CSS accordingly

### CODE REVIEW

**Comment by octplane** [comment]
Oh, yeah, this is the fix for #319, but I should have mentionned that somewhere in the commit msg... 🔥

**Comment by alexcrichton** [comment]
Nice! Thanks!

**Comment by alexcrichton** [comment]
Ok, playing around locally, it looks like there's only two differences that stick out. The lock icon if you're logged out in the top right is a brighter gray and the "crate" icon (purple box in a white circle) has a much larger purple box than before. Do you know if those could get tweaked?

**Comment by octplane** [comment]
Tweaked in #323 
I can probably work on more details if you find other dubious stuff.

**Pull request merged**
