### PR TITLE
Replace "Loading..." screen with progress bar at the top of the page

### PR DESCRIPTION
**Pull request by Turbo87**
Bildschirmfoto 2020-05-01 um 19 15 46

Implemented via https://github.com/tigressbailey/ember-cli-page-progress

r? @pichfl

### CODE REVIEW

**Comment by pichfl** [comment]
How this this hold up in terms of accessibility? Is this announced in some way?

**Comment by Turbo87** [comment]
@pichfl to be honest, I have no idea... I know that there are aria attributes for progressbars, but I'm not aware of the addon using those. do you consider this a blocker or is this something we could retrofit later?

**Comment by pichfl** [comment]
If you get around to refactoring that Addon, please consider adding some improvements. Until then, the new state is not worse than the old.

@bors r+

**Comment by locks** [comment]
I am not a huge fan of progress bars in general (they're usually "lies" 😂), I'd prefer a Knight Rider-stylye spinner to indicate activity, but even then I'm more of a fan of your approach on the index page ;)

**Comment by Turbo87** [comment]
closing this for now until we find a solution 😢

**Pull request closed without merging**
