### PR TITLE
Fix remaining Ember Data problem

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves the remaining issue in #214

### CODE REVIEW

**Comment by alexcrichton** [comment]
[You mention](https://github.com/rust-lang/crates.io/pull/214#issuecomment-156950624) that this is because we're sending `versions: null`, but perhaps we could omit the `versions` key entirely when sending data? That should in theory have the same effect, right?

**Comment by Turbo87** [comment]
That would probably have the same effect, yes. I don't have enough experience with the codebase yet to implement it there though. I would suggest to use the current solution for now and when we later refactor the api we can revisit this problem.

**Comment by Turbo87** [comment]
ah shit, hadn't seen that one yet... I've been writing too much Kotlin lately :wink:

**Comment by Turbo87** [comment]
should be fixed now

**Comment by alexcrichton** [comment]
Thanks!

**Comment by alexcrichton** [comment]
Ok, I've now deployed this, (thanks for all the fixes @Turbo87!)

One issue I see is that the "other downloads" section of the graphs isn't updated when you navigate between crates, for example if you click on the winapi crate and then on the libc crate you see this graph:



but if you reload the page you see:

**Comment by Turbo87** [comment]
awesome! :tada: 

I'll see what I can do about the remaining issue. There is also one more deprecation warning type that I have not fixed yet regarding request metadata. If that one is fixed we are on track to Ember v2.x.

**Pull request merged**
