### PR TITLE
[categories] Add internationalization and localization

### PR DESCRIPTION
**Pull request by behnam**
Background: https://github.com/rust-lang/cargo/issues/4368

# References
* <https://en.wikipedia.org/wiki/Internationalization_and_localization>
* <http://www.i18n.ca/publications/GILT.pdf>
* <http://philip.pristine.net/glit/en/>

# Example Crates

## Category: `internationalizaion`
Almost all libraries that implement Unicode-related functionalities (<https://crates.io/search?q=unicode>), like:
* `unicode-normalization`
* `unicode-bidi`
* `unicode-segmentation`
* `unicode-width`
* `unicode-script`
* `unic`, which covers/will-be-covering all of the above.
* `cldr`
* `accept-language`
* `language-tags`
* `locate-locale`
* `locale`
* `precis`
* `idna`
* https://github.com/servo/rust-icu

## Category: `localization`
There are fewer crates in this category, but still enough to start the category:
* `gettext-rs`
* `litelocale`
* `crowbook-localize`
* `locale`
* `l20n`

### CODE REVIEW

**Comment by carols10cents** [comment]
LGTM! Thank you!!!

bors: r+

**Comment by carols10cents** [comment]
@behnam: we're trying out [bors-ng](https://github.com/bors-ng/bors-ng) in this repo, so @bors isn't going to do anything here, just gotta be patient :)

**Comment by behnam** [comment]
> we're trying out bors-ng in this repo, so @bors isn't going to do anything here, just gotta be patient :)

Uh, right. There's no rush. I though it didn't get the notice because it was not @mentioned, then noticed `bors-voyager` is in work. Thanks anyways. :)

**Comment by carols10cents** [comment]
ok NOW it's stuck :P

**Comment by carols10cents** [comment]
bors: r+

**Comment by notriddle** [comment]
bors ping

**Pull request merged**
