### PR TITLE
Fix users/stats endpoint erroring when the user doesn't own any crate

### PR DESCRIPTION
**Pull request by kureuil**
Spot this while setting up a local instance today, but it seems production is also affected. Because diesel's `sum` returns an error when the sum result is null, the endpoint returned a 500 error and the Dashboard page would not load up.

The fix I applied is making a separate query to count the number of crates owned. Ideally, we should use [COALESCE](https://www.postgresql.org/docs/9.2/static/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL "PostgresQL COALESCE documentation entry") to make it a single query, but I couldn't find any information in Diesel's documentation.

### CODE REVIEW

**Comment by sgrif** [comment]
> Because diesel's sum returns an error when the sum result is null, the endpoint returned a 500 error and the Dashboard page would not load up.

That's a bug in Diesel if so. Can you open an issue there with more details about the specific error that was returned? Are you sure it's about the result being NULL and not `diesel::result::Error::NotFound`?

**Comment by sgrif** [comment]
Actually glancing at the source code for `sum`, this is 100% a bug in Diesel. I would strongly prefer that we fix it there, I can release a minor version with the fix. Can you open an issue on Diesel with the exact error that you're seeing?

I'm going to close this since we shouldn't introduce workaround code here for something that should be quick to fix upstream. @carols10cents Feel free to re-open if you disagree.

**Comment by sgrif** [comment]
https://github.com/diesel-rs/diesel/commit/cf32f6f7

I guess I forgot...

**Comment by carols10cents** [comment]
I'm cool with the fix being in diesel. Great catch @kureuil! I definitely want your test though-- @sgrif I'm assuming you'll make a PR when there's a new diesel version? Could you also cherry pick https://github.com/rust-lang/crates.io/pull/864/commits/ad85196feb7b4bf0c90346d5af1edfc5aadbed47 into that PR when you do so? I'd love for @kureuil to get credit for at least some of their work here ❤️

**Comment by sgrif** [comment]
Yes. I've identified the bug in Diesel and will be releasing 0.13.1 and 0.14.1 shortly. I will cherry-pick that commit. Thank you @kureuil! <3

**Comment by kureuil** [comment]
No problem :)
@sgrif do you still want an issue on diesel's repo ?

**Comment by sgrif** [comment]
@kureuil Nope, I've found it. Thank you! ❤️

**Pull request closed without merging**
