### PR TITLE
Update Ember.js

### LINKED ISSUE #156: Pagination numeric links at bottom of reverse_dependencies don't work
https://crates.io/crates/serde/reverse_dependencies

They link to '#'

screen shot 2015-05-19 at 6 57 38 pm

### PR DESCRIPTION
**Pull request by Turbo87**
This PR aims to continue the Ember.js update process that was started in #152. So far I've only merged the changes from the current `master` branch into the existing `updates` branch.

/cc @stefanpenner @alexcrichton 

resolves #156

### CODE REVIEW

**Comment by Turbo87** [comment]
From what I can tell the "public" side of the Ember app works fine again now, but I haven't been able to test the dashboard and `/me` pages yet. Should I be able to login via GitHub when using `npm start -- --proxy https://crates.io`? This does not seem to work at the moment but I haven't yet had time to investigate why.

**Comment by Turbo87** [comment]
Review of the current state would be appreciated though ;)

**Comment by Turbo87** [comment]
Reading the description of the GitHub OAuth process I don't think that I will be able to test the authenticated application state in any way locally. Any ideas?!

**Comment by Turbo87** [comment]
I've mocked out the authenticated pages and resolved the remaining issues. As far as I can tell this is ready for merging now. If any more issues come up please let me know.

**Comment by stefanpenner** [comment]
Oh awesome, I kept meaning to come back to this...

I can provide ember related feedback, but @alexcrichton is likely the one that will have to provide feedback re: login and so forth.

**Comment by stefanpenner** [comment]
@alexcrichton if you have some cycles to help get this to :ship: that would be awesome.
I would love to continue to help improve (add tests) etc this app, with this landing it will restore community ability to do so.

**Comment by Turbo87** [comment]
@alexcrichton I guess the best way to figure out if there are any more issues is deploying this branch on the staging server for a few days. Who would I need to talk to to make this happen?

**Comment by alexcrichton** [comment]
> Reading the description of the GitHub OAuth process I don't think that I will be able to test the authenticated application state in any way locally. Any ideas?!

I had to set up a local dummy app in GitHub and set the callback URL to http://localhost:4200/authorize/github, after that I was able to develop locally (using the secret/token that GitHub provided)

I'll check this out locally and poke around, thanks for picking this up @Turbo87!

**Comment by alexcrichton** [comment]
OK, poking around, here's some things I found:

* I clicked on a package from the home page and was met with "Version `null` does not exist" as a flash message
* login worked ok
* The "API access" panel [looked a little odd with some spacing](https://i.imgur.com/JncPR3V.png)?
* The "showing stats for" button [seemed to revert in style](https://i.imgur.com/456j0U0.png)
* The crate search page seems to have [lost lines inbetween results](https://i.imgur.com/dUaNBCF.png)

**Comment by dirk** [comment]
@Turbo87: Thank you so much for putting in the effort on updating. Had a hell of a time setting things up a few days ago with all these (relatively) ancient versions of Ember and other packages.

**Comment by Turbo87** [comment]
@alexcrichton thanks for the quick feedback. I've pushed some more commits to fix the mentioned problems.

**Comment by alexcrichton** [comment]
Alright everything checks out for me at least, so I'm gonna go ahead and merge, thanks so much again @Turbo87!

**Comment by Turbo87** [comment]
awesome, thanks! :tada:

**Comment by Turbo87** [comment]
let me know if any more issues come up

**Comment by Turbo87** [comment]
@alexcrichton is crates.io updated automatically or do you have to update it manually?

**Comment by alexcrichton** [comment]
I've gotta update it manually and I hope to do so either later today or tomorrow. I've got a few more Rust-related updates I'd like to land as well.

**Comment by stefanpenner** [comment]
Woooohoo!

**Comment by alexcrichton** [comment]
OK, I managed to deploy this to staging, and it looks like there's only one bug I can find so far. 

For this page, https://staging-crates-io.herokuapp.com, if you click on a crate, go back to the home page, and then click on the `ssh2` crate you'll see the "version null does not exist" error: 



Other than that it looks like it all checks out though!

**Comment by Turbo87** [comment]
> For this page, https://staging-crates-io.herokuapp.com, if you click on a crate, go back to the home page, and then click on the ssh2 crate you'll see the "version null does not exist" error:

I don't seem to be able to reproduce it following you instructions. I've seen it occasionally flash and then go away again on my mobile phone but I thought it might have been the slow connection.

**Comment by Turbo87** [comment]
and just after writing this he discovers how to reproduce it... :see_no_evil: 

1. click on a crate
2. click on the back button of the browser
3. click on the exact same crate again

**Comment by Turbo87** [comment]
I've debugged this to the state where I know what's going on and how to fix it but I'm not sure if it's a bug in ember-data or our own code:

> click on a crate

- the `versions` relationship of the crate is loaded (`async + hasMany`) 

> click on the back button of the browser

- `/summary` is loaded and returns lists of crates with `versions: null`
- `versions: null` is normalized into an empty array and pushed into the store which deletes the versions downloaded in the previous step

> click on the exact same crate again

- since the async relationship is resolved the versions are not downloaded again
- `max_version` can't be found in the now empty `versions` relationship and the error is shown

From what I remember `null` fields should not update any values in the store but it seems that this is not true for relationships. I tend to think that this is actually a bug in ember-data but I'm not sure.

@stefanpenner @bmac any ideas whats going on here?

as a hotfix we can check if `crate.versions == null` and `delete crate.versions` before the `normalize()` method is called, but I'm not sure if that is actually the best way to procede here...

**Pull request merged**
