### PR TITLE
Update installation and first run instructions

### PR DESCRIPTION
**Pull request by Luthaf**
I still get an error with these changes:

```
$ npm run start:local

> cargo@0.0.0 start:local /Volumes/Aldith/Developpeur/crates.io
> ember server --proxy http://127.0.0.1:8888

Cannot find module 'jshint'
Error: Cannot find module 'jshint'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Volumes/Aldith/Developpeur/crates.io/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/index.js:6:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.1.1/bin/node" "/usr/local/bin/npm" "run" "start:local"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! cargo@0.0.0 start:local: `ember server --proxy http://127.0.0.1:8888`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cargo@0.0.0 start:local script 'ember server --proxy http://127.0.0.1:8888'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cargo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember server --proxy http://127.0.0.1:8888
npm ERR! You can get their info via:
npm ERR!     npm owner ls cargo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Aldith/Developpeur/crates.io/npm-debug.log
```

Any idea on how to fix it ?

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks!

**Comment by alexcrichton** [comment]
In the past I've had some success just blowing away node_modules? Not sure if that would work though :(

**Comment by Luthaf** [comment]
> In the past I've had some success just blowing away node_modules

This works!

I got the website running, but there is nothing in the database. Is there any easy way to populate the database with some data?

**Comment by alexcrichton** [comment]
Unfortunately, no, it still needs to be manually propagated

**Comment by Luthaf** [comment]
How can I do that?

**Comment by alexcrichton** [comment]
The best way is to basically make yourself an account and then publish a bunch of crates using `cargo publish --host`

**Pull request merged**
