### PR TITLE
Hold onto authorization header with ApiToken source

### PR DESCRIPTION
**Pull request by joshleeb**
Modify the `AuthenticationSource::ApiToken` variant to hold onto the authorization header that may be used to fetch the current user.

Ref. #1548 (Task 4)

### CODE REVIEW

**Comment by joshleeb** [comment]
@sgrif please take a look 😄

**Comment by markcatley** [comment]
I've used your changes, made some improvements and moved things a little further forward. I'd love your feedback. It is PR #1700.

**Comment by carols10cents** [comment]
I'm really sorry about the long delay on this, but I've resolved the merge conflicts and this looks great! Thank you!

@bors r+

**Pull request merged**
