### PR TITLE
adding badges to crate page

### LINKED ISSUE #114: Badges for latest version of a crate
[Gemfury](http://badge.fury.io/) provides badges that show the latest version of a Rubygem, NPM package, CocoaPod, etc. These are nice to include in a README to avoid having to update a "latest version" section or something.

Rather than going through Gemfury, crates.io could simply provide a URL like `https://crates.io/badges/$package/latest`, which issues a redirect to a [shields.io](http://shields.io/) badge URL containing the necessary information. For example, the `json_macros` badge might redirect to something like `https://img.shields.io/badge/crates.io-json_macros%20=%20%220.1.3%22-brightgreen.svg`:

[crates.io: json_macros = "0.1.3"](https://crates.io/crates/json_macros/0.1.3)

The crate page could then include a handy way to get the Markdown for a crate's badge for the maintainer's convenience.

### PR DESCRIPTION
**Pull request by rjgoldsborough**
fixes #114

### CODE REVIEW

**Comment by steveklabnik** [comment]
This looks sweet; can you maybe toss up a screenshot or two?

**Comment by rjgoldsborough** [comment]
screen shot 2016-08-30 at 8 05 51 am
screen shot 2016-08-30 at 8 06 28 am

**Comment by steveklabnik** [comment]
:heart_eyes: 

@alexcrichton do you have any feelings on this? I'm down to merge.

**Comment by alexcrichton** [comment]
Neat! Maybe we could stick with just the crates.io version one for now though to start out?

**Comment by rjgoldsborough** [comment]
Whatever works for y'all :)

**Comment by steveklabnik** [comment]
Let's do that, then. Will merge after :smile:

**Comment by steveklabnik** [comment]
:confetti_ball:

**Pull request merged**
