### PR TITLE
Improve README styling

### PR DESCRIPTION
**Pull request by Turbo87**
### Before
Bildschirmfoto 2021-03-05 um 23 32 22

### After
Bildschirmfoto 2021-03-05 um 23 32 02

### CODE REVIEW

**Comment by Turbo87** [comment]
I've now also adjusted the code block styling to make it match the new look a bit better :)

### Before
Bildschirmfoto 2021-03-06 um 09 04 27

### After
Bildschirmfoto 2021-03-06 um 09 02 07

**Comment by pichfl** [comment]
Not sure why, but I think I liked the light on dark highlighting. Isn't there a dark version of solarized as well? Are these color schemes at last somewhat adhering to contrast guidelines for the web?

**Comment by Turbo87** [comment]
@pichfl I've rebased and moved the code block styling change out of the PR for now. We can discuss this in a dedicated PR later :)

**Pull request merged**
