### PR TITLE
Issue #563 - Add a "Copy button" for the crates

### PR DESCRIPTION
**Pull request by Insomgla**
A copy button is now displayed to the user if his browser supports ClipboardJS.

Has to be discussed now : how to inform the user that the content has actually been yanked.
    - tooltip: from scratch, using another library ?
    - display a message in an existing element of the page: where, and how to render it nicely ?

### CODE REVIEW

**Comment by carols10cents** [comment]
Awesome!! On first glance this looks good, I'm going to give it a try tomorrow :)

**Comment by Insomgla** [comment]
Sure thing. Again, I still need to figure out how tell the user that the content has been copied (or if there was an error). I would normally use a tooltip for that, but no Javascript library that's already imported does handle tooltips. I could try crafting one from scratch in pure CSS.

**Comment by Insomgla** [comment]
I went very simple on this one, didn't like to import a bunch of Javascript libraries. The information is here, now I'm open to any suggestion on the design or else.

**Comment by Insomgla** [comment]
Any input?

**Comment by elliotekj** [comment]
A couple of things on this for me:

- The button doesn't show at all in Safari 9.x (OS X). 
- The button is using the vendor defaults for styling, it should use one of the button styles previously laid out in Crates' CSS. 

Tested on OS X with the latest releases of Firefox nightly and Chrome and Safari 9.x.

**Comment by Insomgla** [comment]
Thanks ! I'll look at it ;)

**Comment by Insomgla** [comment]
By the way, if the button doesn't show, it's probably because the browser is not supported. At least, the `isSupported()` method probably returns false on your browser.

**Comment by Insomgla** [comment]
I did a little edit on the button's design according to your comment @elliotekj . I tried to use the button style that already exist, but it wasn't really nice. The only buttons already present on the websites are the rounded ones with the gradient-like colors, and I couldn't make it fit with the squarish shape of the crate info div.

**Comment by carols10cents** [comment]
Hi @Insomgla, sorry about the delay!!! This looks great, I've tried it out and it works great!!

One question, what's the license on the copy to clipboard SVG? Did it come from somewhere? Just want to make sure we're allowed to use it before merging :) Thanks!!

**Comment by Insomgla** [comment]
Hi @carols10cent, I used the icon they use on their demo website, which seems to be this one : https://commons.m.wikimedia.org/wiki/File:Octicons-clippy.svg

I am on my mobile so I cannot check if the icons are the same, but if they are, here you go :) If not, I'll replace the svg in my PR with the Wikimedia one.

**Comment by elliotekj** [comment]
@carols10cents @Insomgla Just double checked this: both clipboard.js and octicons, where the icon is from, are licensed under MIT so we're all good.

**Comment by carols10cents** [comment]
Perfect! Thank you for checking, both of you! <3

**Pull request merged**
