### PR TITLE
Assume html if no Accept header is presented

### LINKED ISSUE #163: 404 responce for HEAD request with no Accept:
Steps to reproduce:

> $ curl -I https://crates.io/
> HTTP/1.1 404 Not Found
> <...>
> Content-Type: application/json; charset=utf-8

With Accept: text/html everything is okay:

> $ curl -H "Accept: text/html" -I https://crates.io/
> HTTP/1.1 200 OK
> <...>
> Content-Type: text/html

### PR DESCRIPTION
**Pull request by tamird**
Fixes #163.

@alexcrichton this is currently untested, but I'd be happy to add a test if you have some guidance.

### CODE REVIEW

**Comment by tamird** [comment]
@alexcrichton

**Comment by alexcrichton** [comment]
Thanks!

**Comment by steveklabnik** [comment]
This is causing some confusion https://users.rust-lang.org/t/crates-io-api-endpoint-misbehaving/7974

**Comment by alexcrichton** [comment]
Ok, I've reverted and we can figure out another solution

**Pull request merged**
