### PR TITLE
Ignore auto instead of staging.tmp on Travis CI

### LINKED ISSUE #1603: Update .travis.yml now that we are using Homu
It looks like Homu uses an `auto` branch instead of `staging`.  In our `.travis.yml` file we exclude builds on the `staging.tmp` branch.  This was previously required with `bors-ng`.

We can remove this exception now, but it's not yet clear to me if we need to add a similar rule for Homu.

### PR DESCRIPTION
**Pull request by kzys**
Fixes #1603.

### CODE REVIEW

**Comment by carols10cents** [comment]
Thank you!!

**Comment by jtgeibel** [comment]
Doesn't bors run its tests on auto? I'm not sure this will work.

**Comment by carols10cents** [comment]
Oops. I guess not. @kzys could you change this to just remove the ignoring of `staging.tmp` and the reference to bors-ng, but not ignore `auto`? Thanks!

**Comment by jtgeibel** [comment]
@kzys thanks for looking into this!  I agree with the changes Carol suggests.

It looks like Homu recommends running tests `only:` on the `auto` branch.  While it is rarely used, we currently allow merging via GitHub GUI and allow pushes directly to `master`.  Those could be locked down, but in both cases it looks like someone with `rust-lang` org permissions would need to do that.  So unless we change that, we should continue running tests on all branches for now.

Thanks again!

**Comment by kzys** [comment]
> just remove the ignoring of staging.tmp and the reference to bors-ng, but not ignore auto?

Doesn't it make the entire branches: block empty?

**Comment by jtgeibel** [comment]
LGTM!

@bors r+

**Pull request merged**
