### PR TITLE
Record verified email, if present, of the publisher in the version record

### PR DESCRIPTION
**Pull request by carols10cents**
Connects to #1620. We can start recording emails if we have them, even though we're not requiring verified emails yet.

This builds on top of #1561.

### CODE REVIEW

**Comment by sgrif** [comment]
Since we virtually never want this column outside of storing it for auditing purposes, does it make sense to store it in another table instead of as a column on versions?

**Comment by carols10cents** [comment]
Great idea! That would certainly get rid of the complexity from working around https://github.com/diesel-rs/diesel/issues/1979.

Do the changes from #1561 look ok? Would you rather merge that one and then this one, or only merge this one?

**Comment by sgrif** [comment]
#1561 looks fine overall. I'd probably opt to do a second query to load the publishers, but we can always make those changes later. I have no strong feelings on which we merge first, but I'd probably like to deploy at least once before merging either since we have a lot of code already in master for the next deploy.

**Comment by carols10cents** [comment]
Ok, if both this and #1561 look fine, I'd recommend merging this one, which I think we're ready to do because you deployed today. I'll let you approve though, going to close #1561.

**Comment by jtgeibel** [comment]
This looks good to me.  I've also tested in staging and confirmed that the publishing information is provided in the API and that the verified email address is recorded in the database (but not exposed publicly).

Thanks @Andy-Bell and @carols10cents for your work on this.

@bors r+

**Pull request merged**
