### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by sgrif**
I noticed we had a bunch of functions which weren't being used anymore. I've taken the liberty of deleting them. It was pretty easy. :trollface:

(Note: This includes all my other open Diesel PRs, only the last commit and the deleted binary commits are actually new. I'll rebase this once those are all merged, but yes we really are done)

### CODE REVIEW

**Comment by vignesh-sankaran** [comment]
@sgrif Could you run rustfmt and push up the code again please? :)

**Comment by sgrif** [comment]
The rustfmt changes are from the other PRs, this one has no formatting as it only removes code.

**Comment by carols10cents** [comment]
bors: r+

**Comment by sgrif** [comment]
:tada:

**Pull request merged**
