### PR TITLE
rss: Remove explicit/duplicate XML escaping

### PR DESCRIPTION
**Pull request by Turbo87**
XML tags inside `CDATA` sections don't need to be escaped, so this explicit escaping step led to an unnecessary duplicate escaping being applied.

Related:

- https://github.com/rust-syndication/rss/issues/167#issuecomment-2480138799

### CODE REVIEW

**Review by eth3lbert — COMMENTED** [review]
According to  https://en.wikipedia.org/wiki/CDATA#Nesting, if I understand correctly, we need to encode `]]>` if description contains it.

**Comment by Turbo87** [comment]
I added another commit that explicitly checks for `]]>` escaping and it looks like you discovered a bug in the rss/quick-xml crate(s). It does not appear to get escaped properly. I'll report it over there and see if I can fix it.

**Review by eth3lbert — APPROVED** [review]

**Comment by Turbo87** [comment]
Reported at:

- https://github.com/rust-syndication/rss/issues/173
- https://github.com/tafia/quick-xml/issues/831

**Comment by Turbo87** [comment]
I'll merge this PR for now until the issue is fixed upstream :)

**Pull request merged**
