### PR TITLE
Fix user links CSS

### PR DESCRIPTION
**Pull request by gentoo90**
Before | After
------------ | -------------
before | after

### CODE REVIEW

**Comment by tomaka** [comment]
Ah! This problem has been bothering me for weeks! :heart:

**Comment by alexcrichton** [comment]
Hm when I shrink the size of the windows to be very skinny this causes the menu to look a little funny. The current rendering also looks good to me on Firefox at least. What browser are you using?

**Comment by gentoo90** [comment]
Firefox. Fixed:
after2

**Comment by alexcrichton** [comment]
Hm the text still looks a little scrunched to me on Firefox with a smaller screen:

Before:



After:



Is the `min-width` property still necessary? (removing that made it look ok). To clarify, what browser are you using to view the changes here?

**Comment by gentoo90** [comment]
OK, now I found it, this small-screen menu already has min-width in its style, and it's `200px`.
> what browser are you using to view the changes here?

Firefox and Chrome.

**Comment by gentoo90** [comment]
> Is the min-width property still necessary?

Yes, without it user menu still look like this
before

**Comment by alexcrichton** [comment]
Ah ok, with the higher min-width this looks fine to me, thanks!

**Pull request merged**
