### PR TITLE
Switch to GitHub IDs #645

### PR DESCRIPTION
**Pull request by vignesh-sankaran**
Testing procedure I used was the following:

- Log in as a user
- Upload a crate under that user
- Log out, and log in as another user
- Attempt publishing the crate as the prior user
- Log in as the other user, modify the crate and publish the crate

@carols10cents A couple of things I noticed were that the script exited if an uppercase "Y" was entered, and that there is an assertion that fails if more than 1 crate is being transferred. 

As a matter of interest, when is this script utilised?

### CODE REVIEW

**Comment by vignesh-sankaran** [comment]
Argh I should learn not to use git push --force, lost my changes

**Comment by vignesh-sankaran** [comment]
Argh sorry for the mess, forgot to branch things out :(

**Comment by Turbo87** [comment]
@vignesh-sankaran FWIW you should probably not use your `master` branch for PRs 😉

**Comment by vignesh-sankaran** [comment]
@Turbo87 I've learned that the hard way now :)

**Pull request closed without merging**
