### PR TITLE
WIP: Fix reverse dependencies query

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves https://github.com/rust-lang/crates.io/issues/306

@carols10cents could you check if this is indeed working as intended? I didn't have any crates in my local env to check and only used the unit tests for verification. Is there some sort of sandbox env that we could deploy this too?

This PR only includes the backend changes for now until we have verified that those work as intended.

### CODE REVIEW

**Comment by carols10cents** [comment]
I have a backend setup locally, and we also have staging-crates-io.herokuapp.com that I can deploy to, but there's not too much data there. Will be testing this out in a min!

**Comment by Turbo87** [comment]
@carols10cents would be awesome if you could deploy this to the staging server. there seem to be enough crates on there to verify if everything works as I imagined.

**Comment by carols10cents** [comment]
I just created merge conflicts; I'm going to resolve these, force push, then review/try out/deploy to staging :)

**Comment by sgrif** [comment]
Can you better explain why #306 occurred and how this fixes it in your commit message?

**Comment by Turbo87** [comment]
@sgrif is the cross reference to https://github.com/rust-lang/crates.io/issues/306#issuecomment-310693592 not enough?

**Comment by carols10cents** [comment]
@Turbo87 Bad news, good news, then bad news!

I've got this deployed to https://staging-crates-io.herokuapp.com now, and I'm not sure if the backend changes aren't quite working right or if there's frontend stuff that needs to change?

Here's what I'm seeing:

- Visit https://staging-crates-io.herokuapp.com/crates/rand
- Click on the link to libc under dependencies
- Click the dependent crates link
- The page lists libc twice, where instead it should list rand and num_cpus

The good news is that the original issue seems to be fixed! That is, if I:

- Visit https://staging-crates-io.herokuapp.com/crates/rand
- Click on the link to libc under dependencies
- Click the back button
- The dependency is still listed as libc, rather than the wrong case of changing the dependency name to rand! 🎉

Back to the bad news, this problem happens but it happens on live crates.io too so I'm going to file a new issue 😂 When I:

- Visit https://staging-crates-io.herokuapp.com/crates/libc/reverse_dependencies
- The "back to" link at the top just says "back to", but should say "back to libc"
- Clicking on the "back to" link has no effect
- It says "Displaying 1-2 of 2 reverse dependencies of ", without libc displayed at the end

**Comment by carols10cents** [comment]
I'm going to revert the merge on the master branch, but I'm leaving it deployed to staging for you to play with it :)

**Comment by Turbo87** [comment]
@carols10cents sorry about the confusion, there was indeed still something missing from this PR which is why it was still marked as WIP. I'll reopen as another PR with the necessary frontend changes.

**Pull request merged**
