### PR TITLE
Resolved remaining Ember 1.13 deprecations

### PR DESCRIPTION
**Pull request by Turbo87**
After this PR is merged we should be alright to upgrade to Ember 2.x without any major issues.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nice! I wonder if this different handling of `meta` will auto-fix https://github.com/rust-lang/crates.io/issues/220?

**Comment by Turbo87** [comment]
It shouldn't, but if it does that sure would be great ;)

**Comment by alexcrichton** [comment]
Ah looks like it's still an issue, I went to the main page of crates.io, clicked libc, clicked the home page, clicked winapi, clicked home page, and clicked libc again and the graph was odd.

**Comment by Turbo87** [comment]
that is such a weird problem... I've tried it with those instructions and could reproduce it on first try, but the second, third and fourth time it just worked

**Pull request merged**
