### PR TITLE
Add dropdown box to allow selecting more results per page

### PR DESCRIPTION
**Pull request by daubaris**
#1625

### CODE REVIEW

**Comment by sgrif** [comment]
Rather than adding a dropdown for this, could we just up the default sent by the frontend?

**Comment by daubaris** [comment]
You mean to just increase the `per_page` value to 100 to be the default value instead of 10?
https://github.com/rust-lang/crates.io/blob/922a7c92abbb6e750f4d61595ac13d88c8b63fbf/app/controllers/crates.js#L11

**Comment by sgrif** [comment]
I'd go with either 20 or 50 instead of 100, but yes

**Comment by daubaris** [comment]
Wouldn't be better to leave the dropdown just to provide flexibility for the user or will this cause any performance issues? Just curious.

**Comment by sgrif** [comment]
I'm not sure that a dropdown to configure this really adds that much
value, but I'm open to being convinced otherwise. Does anyone ever use
these to lower the number of records displayed?

On Fri, Jun 14, 2019 at 1:28 PM daubaris <notifications@github.com> wrote:
>
> Wouldn't be better to leave the dropdown just to provide flexibility for the user or will this cause any performance issues? Just curious.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

Thanks,
Sean Griffin

**Comment by kzys** [comment]
FYI, https://metacpan.org/search?size=20&q=foo is having a way to change the page size. https://rubygems.org/search?utf8=✓&query=foo, https://www.npmjs.com/search?q=foo and https://pypi.org/search/?q=foo don't provide the one.

Personally I'd like to increase the default page count to keep it simple.

**Comment by locks** [comment]
Increasing the default page seems like a nice small improvement!

**Comment by sgrif** [comment]
@daubaris Are you interested in amending this to increase the default?

**Comment by carols10cents** [comment]
I'm sorry we've let this PR sit for so long! I'm going to close it since it's gotten out of date and since there's https://github.com/rust-lang/crates.io/pull/1883 that implemented the discussed modifications. Thank you!

**Pull request closed without merging**
