### PR TITLE
Support Cirrus CI badges

### PR DESCRIPTION
**Pull request by jonhoo**
Upstream API: https://cirrus-ci.org/guide/writing-tasks/#embedded-badges

Modeled after https://github.com/rust-lang/crates.io/pull/807.

### CODE REVIEW

**Comment by sgrif** [comment]
@bors: r+

Can you open a PR to Cargo updating the docs for this in https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/manifest.md as well?

**Comment by jonhoo** [comment]
@sgrif already opened in https://github.com/rust-lang/cargo/pull/7119 when I opened this PR :)

**Comment by fkorotkov** [comment]
@jonhoo, thank you! 🎉🍾🎉

**Pull request merged**
