### PR TITLE
Upgrade ember

### PR DESCRIPTION
**Pull request by steveklabnik**
I skipped 2.2.0 because everything was going so smoothly.

All tests pass, I clicked around locally and it seemed to be working fine.

### CODE REVIEW

**Comment by stefanpenner** [comment]
> I skipped 2.2.0 because everything was going so smoothly.

:+1:

**Comment by mmun** [comment]
You should use 2.3.1 as it contains some bugfixes.

**Comment by steveklabnik** [comment]
Thanks @mmun , added.

**Comment by Turbo87** [comment]
@steveklabnik make sure to test the login process and the downloads graph extra carefully, aside from that there shouldn't be any major problems ahead. :)

**Comment by Turbo87** [comment]
@steveklabnik make sure to test the login process and the downloads graph extra carefully, aside from that there shouldn't be any major problems ahead. :)

**Comment by Turbo87** [comment]
@steveklabnik make sure to test the login process and the downloads graph extra carefully, aside from that there shouldn't be any major problems ahead. :)

**Comment by Turbo87** [comment]
@steveklabnik make sure to test the login process and the downloads graph extra carefully, aside from that there shouldn't be any major problems ahead. :)

**Comment by Turbo87** [comment]
@steveklabnik make sure to test the login process and the downloads graph extra carefully, aside from that there shouldn't be any major problems ahead. :)

**Comment by alexcrichton** [comment]
It all checks out with me, thanks @steveklabnik!

**Pull request merged**
