### PR TITLE
Make crates.io compatible with whatsdeployed.io

### PR DESCRIPTION
**Pull request by notriddle**

### CODE REVIEW

**Comment by jtgeibel** [comment]
Thanks @notriddle!  A very minor nit, but would you mind updating this to get rid of the clones and squashing into a single commit?  Something like:

```rust
    #[derive(Serialize)]
    struct R<'a> {
        deployed_sha: &'a str,
        commit: &'a str,
    }
    Ok(req.json(&R {
        deployed_sha: &deployed_sha,
        commit: &deployed_sha,
    }))
```

**Comment by notriddle** [comment]
Done.

**Comment by jtgeibel** [comment]
Awesome, thanks!

**Comment by jtgeibel** [comment]
bors: r+

**Pull request merged**
