### PR TITLE
Rename gitlab to git-lab

### PR DESCRIPTION
**Pull request by ordian**
Follow-up on [comment](https://github.com/rust-lang/crates.io/pull/863#issuecomment-313868440).

### CODE REVIEW

**Comment by imp** [comment]
Documentation at http://doc.crates.io/manifest.html#package-metadata still mentions "gitlab" instead of the "git-lab"

**Comment by ordian** [comment]
Documentation is located in [cargo](https://github.com/rust-lang/cargo/blob/master/src/doc/manifest.md#package-metadata) repository. I'm not sure this change is already deployed.

**Comment by ordian** [comment]
@sgrif I just noticed, that name git-lab is inconsistent with coverage services:
`codecov = { repository = "...", branch = "master", service = "gitlab" }`
maybe we should revert this change?

**Comment by sgrif** [comment]
@ordian My intention was for this change to only affect how we store things internally and how it's sent to the front-end, not affect what's allowed in `Cargo.toml`. I see now that this isn't doing that. I'm going to go ahead and revert. We could probably fix it, but honestly this probably isn't worth the effort for such a small change.

**Pull request merged**
