### PR TITLE
Add an environment variable to let us exclude crate IDs from the recent downloads list

### PR DESCRIPTION
**Pull request by carols10cents**
I haven't figured out a great way to add a test for this because I need to create a crate and get a crate ID and then change the app's config, and the test app doesn't easily have this... so I thought I'd throw up this change for discussion and see if anyone had better ideas.

### CODE REVIEW

**Comment by Turbo87** [comment]
would it be possible to filter by crate name instead? or is the name not available in that table?

**Comment by carols10cents** [comment]
The query does join to the `crates` table, so the crate name is available

**Comment by Turbo87** [comment]
in that case I think you can start a test app with a random crate name in the new config value and then create that crate after the app has started, right?

**Comment by Turbo87** [comment]
given that the particular crate now has almost 1/4 of the downloads of `bitflags` in total, do we also want to exclude it from the "Most downloaded" list?

**Comment by carols10cents** [comment]
Good calls. Updated!

**Comment by Turbo87** [comment]
looks great, thank you! 

one potential follow up: we allow the users to view the list of crates sorted by downloads too, but we don't exclude the crates there. I'm not sure how or if we should deal with that too.

merging anyways since this is a good first step :)

@bors r+

**Pull request merged**
