### PR TITLE
Upgrade Ember and other dependencies where possible

### PR DESCRIPTION
**Pull request by bjornharrtell**
Thought I'd try an Ember and deps upgrade here as an exercise. Almost made it.

## Known TODOs

* [x] Assertion Failed: You attempted to define a `{{link-to "crate.version"}}` but did not pass the parameters required for generating its dynamic segments. You must provide a param `version_num`."
* [x] Assertion Failed: You modified crate.owners twice on <cargo@model:crate::ember764:log> in a single render
* [x] Two test failures

### Before
 - cargo-78d091696888a1996f55b55e06305ed1.js: 326.6 KB (32.12 KB gzipped)
 - cargo-dd3626a8e865f3873803b828b74aec11.css: 18.27 KB (3.91 KB gzipped)
 - vendor-31836fffce5288795738abce6ce5df0a.js: 804.41 KB (219.53 KB gzipped)
 - vendor-db1aae18a50d64dc7d57cc30890fa4a9.css: 1.82 KB (889 B gzipped)

### Ember 2.10
 - cargo-a2ea731112e31eb4ad816a2673775132.js: 195.24 KB (25.6 KB gzipped)
 - cargo-dd3626a8e865f3873803b828b74aec11.css: 18.27 KB (3.91 KB gzipped)
 - vendor-344087d1962d26f87e103b37bb470b18.js: 898.98 KB (234.69 KB gzipped)
 - vendor-924cc62bda01ca298267563aa0a649b0.css: 2.11 KB (969 B gzipped)

### Ember 2.11
 - cargo-1055d8d7726ed3652b8c5b15698dad5f.js: 203.79 KB (26.89 KB gzipped)
 - cargo-87493fb73363b542afc2eb3fb4cd5e3e.css: 18.24 KB (3.91 KB gzipped)
 - vendor-8c012c271ee0b49d3b8c93c77601c24f.js: 906.82 KB (235.8 KB gzipped)
 - vendor-924cc62bda01ca298267563aa0a649b0.css: 2.11 KB (969 B gzipped)

### CODE REVIEW

**Comment by bjornharrtell** [comment]
The link-to issue seems to be an Ember regression, https://github.com/emberjs/ember.js/issues/14657.

**Comment by alexcrichton** [comment]
r? @carols10cents 

Thanks for the PR @bjornharrtell!

**Comment by carols10cents** [comment]
@bjornharrtell It looks like this is still WIP, right? And we'll need to wait on a fix for that ember issue? If so, please ping me when this is ready for review or if you need any help! <3

**Comment by bjornharrtell** [comment]
Had another go so this is now rebased on master and at Ember 2.11. I've worked around the link-to issue and can't reproduce the other issues now so perhaps this is ready for review. Ping @carols10cents. :)

**Comment by carols10cents** [comment]
This is awesome!! I'm so glad you're doing this :) Just three hopefully small things:

1. There's a few merge conflicts; I think I could resolve them but I'd rather you make sure I don't pick the wrong versions. If I promise not to merge any front end code that would cause more merge conflicts in the meantime, would you mind rebasing one more time? :)
2. When I load up the homepage on this branch, there are a few differences in the CSS and I'm not sure why they would have changed :-/ 

screen shot 2017-02-09 at 10 36 17 pm

There's a purple outline around the search box, and the text of the "Browse All Crates", "Docs", and "Log in with github" links is dark. Also, while those header links function correctly as links when I click on them, they don't have `cursor: pointer` on hover :(

3. There's a warning about `pretender` in the [travis logs](https://travis-ci.org/rust-lang/crates.io/builds/198166614#L864) during the frontend test runs. While it is just a warning, it's not happening on master, so I wonder if we need to be doing something differently?

**Comment by bjornharrtell** [comment]
You are welcome :) Worked through the merge conflicts.

I would assume any visual change could be explain by some dependency upgrade (besides ember), but I cannot reproduce the purple outline. The dark links and cursor issue is fixed, it was caused by changes in normalize-css.

Not sure how to fix the pretender warning.

**Comment by carols10cents** [comment]
Thank you for fixing the merge conflicts and the normalize-css!!

I poked at the purple outline around the search box-- it only happens for me in firefox. If I put some white behind it instead of the dark green, then the outline looks red. And-- wait for it-- if I remove the `required` attribute from the `input`, it goes away :) 

I considered removing the `required` attribute, but [adding it was deliberate](https://github.com/rust-lang/crates.io/pull/477), soooo i'm going [to throw `box-shadow: none`](https://github.com/twbs/bootstrap/issues/21323) on the search box and call it a day.

As far as the Pretender warning, that was a fun one to chase down 😌 Along the way I found the mirage upgrade docs which said everything should be in /mirage rather than /app/mirage now. After trying many things recommended in various mirage bug reports, I found [this issue](https://github.com/samselikoff/ember-cli-mirage/issues/1000) that mentioned [this change](https://github.com/samselikoff/ember-cli-mirage/pull/984) to the blueprints that was included in 0.2.5, so I regenerated the mirage files, indeed picked up a change that shuts down the server after each acceptance test, and it seems to be working.

Pushed to your branch to let CI run, I'll merge when it passes!!! 🎉

**Comment by carols10cents** [comment]
And we're green! Thank you!!!!

**Pull request merged**
