### PR TITLE
Bump actions/cache from v1 to v2

### PR DESCRIPTION
**Pull request by imbsky**
We just released v2. That includes a lot of improvements.
https://github.com/actions/cache/releases/tag/v2.0.0

### CODE REVIEW

**Comment by imbsky** [comment]
@JohnTitor I added a commit, so we may need an additional review.

**Comment by JohnTitor** [comment]
Hm, you shouldn't add any commit after r+ otherwise we couldn't merge PRs fully. Anyways I wouldn't prefer 02d1e20dcfb4cb73ac253eeb2ef3d777c6bff5c4, 46eadc3 is enough here imo.

**Comment by imbsky** [comment]
Oops, sorry. I reset to that point.

**Pull request merged**
