### PR TITLE
Cleanup Ember dependencies

### PR DESCRIPTION
**Pull request by Turbo87**
This PR updates and cleans up some of the npm and bower dependencies of the Ember app in this repository.

Most notable:

- Import `ember-source` from npm instead of `ember` from bower
- Replaced `lodash` dependency with a 5 line function

/cc @locks

### CODE REVIEW

**Comment by Turbo87** [comment]
@locks just told me about https://github.com/rust-lang/crates.io/issues/768 which I unfortunately hadn't seen before... this PR here does not touch ember, ember-data or ember-cli though and my local tests seemed to work fine so I'm confident that this list of updates does not have the same issue as #768.

**Comment by Turbo87** [comment]
@sgrif @carols10cents it appears that the build is failing due to unrelated reasons (``binary `diesel` already exists in destination as part of `diesel_cli v0.13.0` ``). any ideas?

**Comment by carols10cents** [comment]
@Turbo87 sorry about that, we added caching to travis. [It should be fixed now](https://github.com/rust-lang/crates.io/pull/777), could you try rebasing on master please?

**Comment by Turbo87** [comment]
@carols10cents no problem. rebased, let's try again :)

**Pull request merged**
