### PR TITLE
New interface (live preview)

### PR DESCRIPTION
**Pull request by alx741**
This is a very subjective topic. Personally I don't like the **crates.io** interface too much, so I thought experiment a bit and come up with a proposal.

**NOTE**: The live preview was down, I'm currently trying to bring it back
Here is a **live version** of this PR (beware: very slow free hosting):
http://hades.comli.com/

Just the index has been modified, because before I take the extra time and effort of taking the rest of the page to the new design I would like to know if you guys are interested on it and if this PR is actually useful and a candidate to be merged. It would be inefficient to do the rest before knowing if this is actually useful for the project. (Responsiveness is part of that _to do_ work, of course).

Some new icons were created (using GIMP)  for both the header navigation bar and the footer, but also modified the _crates_ and _downloads_ badges to fit the theme.

**Edit**
The per-crate page won't work in the live version, so here are some screenshots:

Index page:
index1
index2

per-crate page:
crate1
crate2

### CODE REVIEW

**Comment by steveklabnik** [comment]
/cc @rust-lang/core 

we have talked about doing a UI refresh, but it wasn't 100% clear what it should be.

**Comment by aturon** [comment]
This is a nice re-skinning!

I'm putting this on the agenda for this week's core team meeting (on Wednesday).

**Comment by pcwalton** [comment]
I suggest using Helvetica exclusively instead of Helvetica + Verdana + Times New Roman

**Comment by nikomatsakis** [comment]
I suggest comic sans

**Comment by erickt** [comment]
It looks nice! The responsive design is having some bugs though, where the various elements overlap or get obscured.

**Comment by alx741** [comment]
> I suggest using Helvetica exclusively instead of Helvetica + Verdana + Times New Roman 

I'll try that out!

> It looks nice! The responsive design is having some bugs though, where the various elements overlap or get obscured.

Oh! yeah, I didn't pay attention to responsiveness whatsoever, just wanted to sketch out a first tentative, avoiding to much work before having some feedback. I'll take care of responsiveness and some refactoring and cleaning that is needed before going further.

**Comment by rjgoldsborough** [comment]
I was curious about this as well.

Any updates or plans to move forward with a redesign?

**Comment by steveklabnik** [comment]
@rjgoldsborough no updates, but we do want to do it at some point.

That said, my memory of this PR is basically "everyone is fairly favorable, though has minor issues"

**Comment by steveklabnik** [comment]
/cc @rust-lang/core 

Reading the comments here, I think that we may have talked about this, but then somehow missed actually putting the result of our comments in this PR, which is a shame.

**Comment by alx741** [comment]
Extra work needs to be done with this like improve responsiveness and port some other pages the the style, but as I said I didn't want to invest too much time on it without first knowing if it's worth it, that is, if you guys like it and are willing to use it (merge). So i was actually waiting to hear some news about the core meeting where this was discussed (?)

**Comment by steveklabnik** [comment]
cc @carols10cents

**Comment by alx741** [comment]
Installation:
Imgur

Loading:
Imgur

Mobile (responsiveness):
Imgur
Imgur
Imgur
Imgur

**Comment by vi** [comment]
> Something Went Wrong!

Seems not working.

**Comment by aturon** [comment]
@steveklabnik

> Reading the comments here, I think that we may have talked about this, but then somehow missed actually putting the result of our comments in this PR, which is a shame.

Yep, looks like it.

The basic feeling at the meeting was: no one is a huge fan of the current crates.io visual design, and this proposal seems like a clear improvement. So, modulo vetting to make sure this is working reliably across all the contexts we care about without losing functionality, we're open to moving forward.

I also want to make clear that there's been a plan to contract with a web design firm to overhaul all of our sites. That got pushed aside in 2016 in favor of other priorities, but is still on the docket for 2017. Now, it's possible that we would scale that down to *just* cover the main site, and not aim for consistency across the sites. But I want to make sure everyone knows there's a chance that there will be a complete overhaul in the future.

**Comment by carols10cents** [comment]
> The basic feeling at the meeting was: no one is a huge fan of the current crates.io visual design, and this proposal seems like a clear improvement. So, modulo vetting to make sure this is working reliably across all the contexts we care about without losing functionality, we're open to moving forward.
> 
> I also want to make clear that there's been a plan to contract with a web design firm to overhaul all of our sites. That got pushed aside in 2016 in favor of other priorities, but is still on the docket for 2017. Now, it's possible that we would scale that down to just cover the main site, and not aim for consistency across the sites. But I want to make sure everyone knows there's a chance that there will be a complete overhaul in the future.

Given that I've let this sit for a long time (I'm sorry @alx741) and other features have been added to the display in the meantime, and given that we might be overhauling the visual design completely, I'd rather not change the visual design in this way at this time. 

I'm mostly worried about a who-moved-my-cheese sort of reaction from the community, and if we go through feedback/revisions/etc to the design in this PR and then we move everyone's cheese *again* with a complete overhaul, that will lead to more frustration and complaints from crates.io users than if we go through a design process involving the community once.

@aturon if you disagree, let's chat :)

Again @alx741, I'm really sorry about this sitting so long without resolution.

**Pull request closed without merging**
