### PR TITLE
Revert to release version of ring

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Doesn't seem to cause compile issues.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
🎉 build passed

**Comment by carols10cents** [comment]
Yep, and my tests failed locally on master too, and if I deleted my test database and recreated it, they passed. So personal problem.

Let's try out the new homu setup!

@bors: r+

**Comment by ishitatsuyuki** [comment]
Rebased.

**Comment by jtgeibel** [comment]
@ishitatsuyuki I think the updates to Cargo.lock were missed in the rebase.

**Comment by ishitatsuyuki** [comment]
Fixed.

**Pull request merged**
