### PR TITLE
Add routing documentations

### PR DESCRIPTION
**Pull request by Turbo87**
This PR adds documentation comments to several route handlers on the front- and backend code.

### CODE REVIEW

**Comment by steveklabnik** [comment]
yay docs!

**Comment by Turbo87** [comment]
if this is merged we could at some point use the crate documentation as our API reference. it currently looks like this:

bildschirmfoto 2015-11-05 um 12 51 41

bildschirmfoto 2015-11-05 um 12 51 32

**Comment by Turbo87** [comment]
ehm... the duplicate "the" is fixed now :wink:

**Comment by Turbo87** [comment]
bildschirmfoto 2015-11-05 um 15 20 18

**Comment by alexcrichton** [comment]
Nice! Makes me want to set up `gh-pages` for these docs so they're always available :)

**Comment by Turbo87** [comment]
I can look into that tomorrow. I've set it up for several of my repos. Should be straight forward by now :wink:

**Pull request merged**
