### PR TITLE
Better error reporting on invalid upload request

### PR DESCRIPTION
**Pull request by ordian**
See [comment](https://github.com/rust-lang/crates.io/pull/801#issuecomment-313859341).

### CODE REVIEW

**Comment by sgrif** [comment]
Can you explain what this commit does in the message, and why it improves the error reporting? (Probably mention the problem linked in that comment, and what the message is now)

**Comment by ordian** [comment]
Sure, the problem is that after switching to serde we're returning custom serde error, for which debug implementation doesn't look nice. Solution to this problem is to use display (to_string) implementation instead of debug.
[play example](https://play.rust-lang.org/?gist=b4a474f60d6fc782303d88e8d34f8061&version=stable)
with debug format:
```
ErrorImpl { code: Message("invalid value: string \"name\", expected ERROR MESSAGE"), line: 0, column: 0 }
```
with display:
```
invalid value: string "name", expected ERROR MESSAGE
```

**Comment by sgrif** [comment]
I'd love to see that in the commit message. :smile:

**Comment by carols10cents** [comment]
Love it, thank you!!! ❤️

**Pull request merged**
