### PR TITLE
Add a tool to generate test data

### PR DESCRIPTION
**Pull request by achanda**
Sometimes, it's easier to work on UI changes with some test data.
This script can be modified later to add more functionality if
necessary.

### CODE REVIEW

**Comment by achanda** [comment]
@alexcrichton does this look useful?

**Comment by alexcrichton** [comment]
Did this end up providing a useful data set to work off? In the past I've found that manually generating data like this is a little lossy in the sense that it's not very complete (e.g. lots of model connections would be missing here). It may be better to script hitting the API endpoints perhaps?

**Comment by achanda** [comment]
The data this generated was fine for my use, I just wanted to see something for search results etc. But yeah, I do agree that the API should be used in general.

**Comment by mschmo** [comment]
What about pulling a dump of the staging DB and importing it to the developer's DB?

**Comment by carols10cents** [comment]
I've decided to close this since it's over a year old. The test data this generates isn't quite what gets generated on the live site, so I'm worried it wouldn't be close enough for accurate testing. I think the `yarn run start:staging` is a better option for working on the frontend locally with data that's more real.

**Pull request closed without merging**
