### PR TITLE
Update license-exprs crate to support SPDX 3.6

### PR DESCRIPTION
**Pull request by carols10cents**
cc @kemitchell, https://github.com/rust-lang-nursery/license-exprs/pull/30

### CODE REVIEW

**Comment by carols10cents** [comment]
I'm not sure why this is showing the travis build as still queued, when I click on it, it says it passed.

**Comment by Lokathor** [comment]
I've sometimes seen people fix glitches like this by closing and re-opening a PR to force github and CI to evaluate it all a second time. Dunno if that would help here.

**Comment by kemitchell** [comment]
Anyone with perms on Travis CI should be able to click a button to restart the build.

**Comment by Lokathor** [comment]
The build passed, the problem is that github isn't displaying it that way.

**Comment by carols10cents** [comment]
This has been deployed!

**Pull request merged**
