### PR TITLE
gitignore: Add .idea directory

### PR DESCRIPTION
**Pull request by hi-rustin**

### CODE REVIEW

**Comment by Turbo87** [comment]
@hi-rustin 👋 

these kinds of files should usually be put in your [global `.gitignore` file](https://docs.github.com/en/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer), to avoid having to add these kinds of files for all the different editors that exist.

**Comment by hi-rustin** [comment]
> @hi-rustin 👋
> 
> these kinds of files should usually be put in your [global `.gitignore` file](https://docs.github.com/en/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer), to avoid having to add these kinds of files for all the different editors that exist.

It seems we already have `.vscode`.

**Comment by Turbo87** [comment]
> It seems we already have `.vscode`.

true, though IMHO we shouldn't have added that one either.

btw there is more information on that at https://github.com/github/gitignore#a-collection-of-gitignore-templates :)

**Comment by hi-rustin** [comment]
> > It seems we already have `.vscode`.
> 
> true, though IMHO we shouldn't have added that one either.
> 
> btw there is more information on that at https://github.com/github/gitignore#a-collection-of-gitignore-templates :)

Got it. Do we need to remove it? If not please feel free to close the pr.

**Comment by Turbo87** [comment]
> Do we need to remove it?

I didn't want to step on anyone's toes, which is why I hadn't removed it, but IMHO we probably should. I'll put this PR on the agenda for our team meeting on Discord later today so we can quickly discuss this.

**Comment by Turbo87** [comment]
@hi-rustin we just discussed this, and removing the `.vscode` stuff is fine with everyone. I'll close this PR here to avoid confusion, but feel free to open a new one where `.vscode` is removed :)

**Pull request closed without merging**
