### PR TITLE
Increase default results per page for crates page

### PR DESCRIPTION
**Pull request by nkanderson**

### CODE REVIEW

**Comment by nkanderson** [comment]
Related to #1625 and #1762, I was looking for something straightforward to get started with. It looked like that PR was maybe stale, but I can find another issue if there's a desire to wait longer for the PR author to respond.

**Comment by carols10cents** [comment]
Thank you so much! This looks great!

@bors r+

**Comment by nkanderson** [comment]
😄 excited about my first contribution to crates.io!

Does this supersede #1625 such that it should be closed?

**Comment by carols10cents** [comment]
Thank you so much for your contribution!! 🎉 Let me know if you're interested in contributing more -- I'm happy to help figure out good issues to work on or answer any questions!

I think this does mean we can close #1625, thank you for reminding me!

**Comment by nkanderson** [comment]
Definitely! Yeah, I'm interested in contributing more, and was hoping to try something within the Rust part of the codebase. If there are issues you think would be good to check out, I'm up for taking a look and finding one to take on!

**Comment by carols10cents** [comment]
I just added some detailed instructions to [this issue](https://github.com/rust-lang/crates.io/issues/1360 ), what do you think? (there's someone who says they're working on it but that was quite some time ago, so I think it's up for grabs again) Let me know if it's not what you're interested in or if you have any questions!

**Comment by carols10cents** [comment]
Whoops, just saw this! Glad you got mailgun figured out. 

> Do you have any recommendations for setting up multiple users to test with? It seems like the auth flow through github makes it a little tricky if I want to log in as different users.

Yes, this is a bit unfortunate. Under github's terms of service, you're allowed to have one human account and [one "machine account"](https://help.github.com/en/github/site-policy/github-terms-of-service#3-account-requirements) (an account you create for performing automated tasks). I usually test multi-user things using my "machine account". Does that work for you?

**Comment by nkanderson** [comment]
Oh cool, that should work great, nikbot5000 will soon be a prolific contributor to my local crates.io 😄

Thanks!

**Pull request merged**
