### PR TITLE
Update contribution guidelines to use --index

### PR DESCRIPTION
**Pull request by Deedasmi**
Introduced in https://github.com/rust-lang/cargo/pull/4209

### CODE REVIEW

**Comment by kureuil** [comment]
Thanks for the pull request @Deedasmi :)

If I remember correctly cargo isn't automatically updated, so wouldn't it be safer to keep the old flag in the documentation, and specify the version ranges compatible with each flag (of course, we'd make `--index` the default) ?

What happens when you run `cargo publish --host file:///path/to/your/crates.io/checkout/tmp/index-co` on the latest cargo version ?

**Comment by Deedasmi** [comment]
A friendly deprecation warning saying --host is no longer valid, and that it will 'soon' become a hard error. 

I do believe `rustup update` automatically updates cargo, so most should be getting updated sooner rather than later. I'm cool with adding a footnote or just closing this and revisiting it later, after a couple more updates.

**Comment by kureuil** [comment]
I think leaving a footnote for old versions of cargo is enough for now :+1:

**Comment by carols10cents** [comment]
Love it!!! Thank you!! 

bors: r+

**Pull request merged**
