### PR TITLE
WIP: Refactor workspace layout

### PR DESCRIPTION
**Pull request by Turbo87**
Having a single `src` folder for one package, but then another package inside of it (`s3`), and then also two bins that rely on a module in a subfolder of `src/bin` has confused me quite a bit. This PR is an attempt to move to a more standardized workspace layout, with a single top-level `src` folder that contains the `cargo-registry`, `cargo-registry-s3` and `on-call` packages.

This should allow us to easily add more internal packages in the future. One example would be to pull the database/schema-related code into its own package, so that the `on-call` package does not have to pull in all the unrelated code from `cargo-registry`.

r? @jtgeibel

### CODE REVIEW

**Comment by Turbo87** [comment]
looks like *something* is still missing to make the tests work. not sure what though... 😅

**Comment by JohnTitor** [comment]
Note that this causes a lot of conflicts and diff-noise. I _really_ oppose this unless you strongly need it.
The current structure is a common pattern enough (putting the _main_ crate to `src` and binary utils as `bin`, though `s3` is indeed unclear a bit, but it can be addressed by the below).

> two bins that rely on a module in a subfolder of src/bin

It makes sense for me as the `on_call` module is for bin utils.

> This should allow us to easily add more internal packages in the future. 

I don't think so. We can add them easily enough even now, like:

```toml
[workspace]
members = [
  ".", # `cargo-registry`
  "yet_another_crate", # `./yet_another_crate`
  "s3" # we could also move the `s3` dir to the root and do this, if you want. Currently, it's equal to `src/s3`.
]
```

> but then another package inside of it (s3)

This can be resolved by the above workspace config, we don't have to do huge moving like this.

**Comment by jtgeibel** [comment]
I have some concerns with this as well. I recall reading that IDE support for workspaces was incomplete, but I can't remember if that was RLS and/or rust-analyzers. It's also possible those issues have been addressed by now, as my recollection is probably from 1+ year ago.

> two bins that rely on a module in a subfolder of src/bin

Yeah, this is a little strange. I think this is best addressed by our plan to consolidate info fewer bins. Linking all these bins uses lots of RAM and is slow even when using lld (`RUSTFLAGS="-C link-arg=-fuse-ld=lld"`). I think `server` and `ops` binaries would be sufficient. (See also #1504 on the developer experience roadmap.)

> but then another package inside of it (`s3`)

It would be nice if we could switch to an external crate for this functionality. Alternatively, I'd be fine absorbing this file into our main library. I don't think there is much benefit to keeping this as a separate crate within our tree.

> One example would be to pull the database/schema-related code into its own package [...]

I think this is a great idea. Given the database dumps, it's possible there would be benefit to publishing this as a public crate that consumers of our exports could use.

I agree with @JohnTitor and would prefer to avoid moving all the existing code under `src/cargo-registry`. In particular, so that it is easier to back this out if we do run into issues with IDE support. I think an initial trial with the `s3` sub-crate would be a good start.

**Comment by Turbo87** [comment]
sounds reasonable. thanks for the details :)

**Pull request closed without merging**
