### PR TITLE
Address new clippy suggestion

### PR DESCRIPTION
**Pull request by jtgeibel**
r? @JohnTitor

### CODE REVIEW

**Review by Turbo87 — APPROVED** [review]
I assume this is better because it doesn't cause a `Vec` allocation?

**Comment by jtgeibel** [comment]
Yeah, I think that is the intent of the lint. The lint is `clippy::needless_collect` which looks like it landed in late 2018, so I think it is now detecting a new variation. Performance of this test though is clearly not a concern.

**Comment by Turbo87** [comment]
yeah, makes sense. feel free to r=@Turbo87 if you want.

**Pull request merged**
