### PR TITLE
Fix intermittent badge::update_crate.

### LINKED ISSUE #546: Nightly build broke
Not entirely sure why because the PRs all passed, but i'll look into it tonight.

https://travis-ci.org/rust-lang/crates.io/builds/198708315

### PR DESCRIPTION
**Pull request by Susurrus**
Failure introduced in 4ce099b.

Closes #546

### CODE REVIEW

**Comment by Susurrus** [comment]
The first commit should fix the intermittent failures bug but I got frustrated when I was extending these badge tests originally because it was all one big test with a lot of continuing state throughout the test. I added the second commit (which I'll be fixing tonight) to break these up into better stop understand tests. There were also some things that weren't properly tested in the old huge test (like a test for adding an appveyor badge without a required field), so I added those tests in this refactoring. If you'd rather I break them out as a separate commit I can do that as well.

**Comment by carols10cents** [comment]
I'm fine having it in the same PR, I'm just not going to merge it til you've got the tests passing, whenever you have a chance is fine! :)

**Comment by Susurrus** [comment]
Will do, now that you documented the pgsql stuff (thanks, btw!), I'll get the tests working locally instead of trying to just use Travis to do everything! Very slow that way.

**Comment by Susurrus** [comment]
@carols10cents got tests working locally which sped things up and I think this PR should be good to go. I snuck in a GitLab capitalization fix that is also necessary.

**Comment by carols10cents** [comment]
Awesome, looks great!

**Pull request merged**
