### PR TITLE
Added encoding declaration

### PR DESCRIPTION
**Pull request by thesayfulla**
You can read more about [here.](https://docs.python.org/3/reference/lexical_analysis.html#encoding-declarations)

### CODE REVIEW

**Comment by Turbo87** [comment]
> If no encoding declaration is found, the default encoding is UTF-8.

if the default is already utf-8 then what is the advantage of explicitly specifying it?

**Comment by thesayfulla** [comment]
> > If no encoding declaration is found, the default encoding is UTF-8.
> 
> if the default is already utf-8 then what is the advantage of explicitly specifying it?

Reason is clarity, self-documentation, and future-proofing like this [script.](https://github.com/AlmaLinux/albs-sign-file/blob/main/db_manage.py)

**Comment by Turbo87** [comment]
unless I'm missing something there is only ASCII in this file anyway, so even if Python decided to change the default it seems quite unlikely to break.

I'm not a big fan of unnecessary visual clutter, so unless there is a good technical reason for this I'm not sure we should add this.

**Comment by LawnGnome** [comment]
Thanks, but given that this script would undoubtedly be broken by more than a default encoding change in a future Python major version that changed it, I don't think this is necessary.

**Comment by thesayfulla** [comment]
Thank you for your time and feedback.

**Pull request closed without merging**
