### PR TITLE
Bump r2d2

### PR DESCRIPTION
**Pull request by jtgeibel**
`cargo update -p r2d2`

Refs: #1805

### CODE REVIEW

**Comment by jtgeibel** [comment]
We should do the deploy, merge, deploy dance on this one, just to be safe.

**Comment by smarnach** [comment]
This pulls in two new versions of `parking_lot` (in addition to the two versions we've already been using), so there is definitely some potential for things going wrong there.

I can't deploy, so I'm randomly selecting
r? @carols10cents 
as new assignee.

**Comment by jtgeibel** [comment]
> This pulls in two new versions of parking_lot (in addition to the two versions we've already been using)

Yeah, this is unfortunate.  (Although the duplication isn't quite that bad, as one pair is `parking_lot` and the other `parking_lot_core`.)  Long term, I'm hoping to get this under control, but its difficult because we effectively can't run `cargo update` at this time.

In terms of build time, it especially bad that we pull in 3 or 4 versions of `syn` and `quote`.  Fortunately, these are both 1.0 now so as we update other things those should consolidate.

**Comment by carols10cents** [comment]
I'm good with this, but I don't want to do this at the same time that we're switching to cloudfront, so I'll do the deploy-merge-deploy dance on Wednesday.

**Comment by carols10cents** [comment]
Dance time!!!

@bors r+

**Pull request merged**
