### PR TITLE
Fix link in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by elliotekj**
There was a line break and a space in the middle of the "E-Mentor" URL resulting in this:

screen shot 2017-06-14 at 11 53 05

This PR just fixes the links formatting.

### CODE REVIEW

**Comment by elliotekj** [comment]
Hmm. Haven't worked with git rebase before and think I've made a mess of this. @carols10cents should I start this PR again or is the above the expected output of a rebase?

**Comment by carols10cents** [comment]
@elliotekj Don't worry about it, I can take care of it :)

**Comment by carols10cents** [comment]
I cherry-picked your commit onto master-- thank you!!

**Comment by elliotekj** [comment]
@carols10cents Thanks! 😄

**Pull request closed without merging**
