### PR TITLE
Make /install work under FastBoot

### PR DESCRIPTION
**Pull request by kzys**
Will add nginx.conf change after #1907. Early feedback is welcome!

### CODE REVIEW

**Comment by jtgeibel** [comment]
What do you think about converting `app/routes/crate/repo.js` and `app/routes/crate/docs.js` in this PR as well?  It seems like the `_redirectTo` logic could be shared between these routes.

(`app/routes/github-login.js` sets `window.location` as well, but supporting login without JS is a whole other thing, if we decide to support that use case.)

**Comment by kzys** [comment]
Sure. I can do that. But please deploy/enable `/policies` change first.

**Comment by jtgeibel** [comment]
> But please deploy/enable `/policies` change first. We should not enable three or four FastBoot-enabled routes at once, especially since we don't have any yet.

I agree, we should enable that first.  That change is deployed now, but I don't have the ability to enable it on production, and I can't speak for @carols10cents on when that will be possible.

**Comment by jtgeibel** [comment]
Looks good to me!

This should be safe to deploy at any time, as no changes are made to nginx.

@bors r+

**Pull request merged**
