### PR TITLE
Fixing issues with owner invites and renamed accounts

### PR DESCRIPTION
**Pull request by carols10cents**
Pushing commit by commit to demonstrate test failures and fixes

### CODE REVIEW

**Comment by sgrif** [comment]
Since you're looking into this, https://github.com/rust-lang/crates.io/pull/1586 is still open and goes after the deeper problem, which is more than just owner invites

**Comment by carols10cents** [comment]
Yep, it'd be great if you'd rebase that PR and address the comments smarnarch left! AFAICT the test I've added in this PR would still fail on that branch, though, so to fix the immediate problem a user is experiencing, that PR won't help.

**Comment by carols10cents** [comment]
I'm happy to squash the format commit in before merging, but didn't want to mess up the test result demonstrations I already did. This is ready for review now; see email for context.

**Comment by jtgeibel** [comment]
Okay, I finally understand the subset of accounts this applies to and how it relates to the other PR.  This looks good to me.

@bors r+

**Pull request merged**
