### PR TITLE
Added badges for Is it maintained, codecov and coveralls

### PR DESCRIPTION
**Pull request by nisargthakkar**
Adding the badges to address #705 and #706

The badges added are:
Is it maintained: Resolution time
Is it maintained: Percentage of open issues
Codecov: Code coverage
Coveralls: Code coverage

### CODE REVIEW

**Comment by nisargthakkar** [comment]
@carols10cents Can you review this PR?

Corresponding PR in the cargo reqpository: https://github.com/rust-lang/cargo/pull/4038

**Comment by nisargthakkar** [comment]
Hey @carols10cents Can you retrigger the travis ci build? These errors no longer pop up locally when I do cargo test. Plus the line numbers that travis suggests has errors doesn't contain the relevant code

**Comment by nisargthakkar** [comment]
I don't think Travis CI is taking the latest push for building as the error reported is:

error: no associated item named `update_crate_old` found for type `cargo_registry::Badge` in the current scope
   --> src/tests/badge.rs:222:5
    |
222 |     Badge::update_crate_old(req.tx().unwrap(), &krate, badges).unwrap();
    |     ^^^^^^^^^^^^^^^^^^^^^^^

But this statement has now moved to L216. Similarly, all other errors are also off by similar line counts

@carols10cents What can I do to run the build with the lates code changes?

**Comment by carols10cents** [comment]
I think the problem is that I pushed code that removed the `Badge::update_crate_old` function :-X I'm going to try fixing up your branch (since I broke it) and pushing a new commit.

**Comment by nisargthakkar** [comment]
Thanks @carols10cents

**Comment by alexcrichton** [comment]
ping @carols10cents, mind taking a look at this?

**Comment by carols10cents** [comment]
Whoops, crates.io has been on my back burner lately. Will hopefully review this tonight!

**Pull request merged**
