### PR TITLE
Make / work under FastBoot

### PR DESCRIPTION
**Pull request by kzys**
This PR adds a transparent cache called "fetcher" to prevent making 2 XHRs
(both from the frontend to the backend).

### CODE REVIEW

**Comment by smarnach** [comment]
@carols10cents @jtgeibel Would any of you be able to take this review? Frontend reviews tend to take me ages, since I just don't know JS and Ember very well, and currently I don't manage to find the time. (I hope this will get better again next year.)

**Comment by carols10cents** [comment]
No problem!

r? @carols10cents

**Comment by kzys** [comment]
Yes. Login, logout and "This site requires JavaScript to be enabled." message are known issues and tracked by #1811. I'd like to keep them open and address them separately to a big PR. Let me know if you (or the team) are not comfortable regrading the approach.

Regarding nginx.conf, can you review #1907? I'd like to have him changes on master first to avoid conflicts.

**Comment by carols10cents** [comment]
> Yes. Login, logout and "This site requires JavaScript to be enabled." message are known issues and tracked by #1811. I'd like to keep them open and address them separately, instead of having a big PR. Let me know if you (or the team) are not comfortable regrading the approach.

Oooops. You caught me-- I haven't actually read through #1811 😆🤭 What you're doing is fine ❤️ 

> Regarding nginx.conf, can you review #1907? I'd like to have him changes on master first to avoid conflicts.

#1907 has been merged in so I merged master into this branch and I'm now deploying this branch to staging to try the different modes out :)

**Comment by carols10cents** [comment]
Hmmm, so I have 9b4aaf5 deployed to staging, which contains the nginx changes, and `USE_FASTBOOT` is set to `staging-experimental`.

However, when I visit https://staging.crates.io/ with JavaScript disabled, I'm seeing only the "This site requires JavaScript to be enabled." notice. I'm not sure why...

**Comment by kzys** [comment]
Yeah, that's odd and I can repro the issue. Seems CloudFront is not caching and the request is coming from Express. Then it should be server-rendered,  but it's not.

```
% curl --dump-header - --silent -H 'Accept: text/html' 'https://staging.crates.io/'                                                                                       
HTTP/2 200                                                                                                                                                                
content-type: text/html; charset=UTF-8
content-length: 2952
server: nginx
date: Fri, 20 Dec 2019 16:38:30 GMT
x-powered-by: Express
accept-ranges: bytes
cache-control: public, max-age=0
last-modified: Thu, 19 Dec 2019 21:30:20 GMT
etag: W/"b88-16f201191e0"
strict-transport-security: max-age=31536000
via: 1.1 vegur, 1.1 9046e5a276a05e60ee34c8475e92b8e7.cloudfront.net (CloudFront)
vary: Accept-Encoding,Accept,Accept-Encoding,Cookie
x-cache: Miss from cloudfront
x-amz-cf-pop: SEA19-C2
x-amz-cf-id: 4R1Ze01jN1Ytyp4Nwdr6JaMVXzHVVp2bL3LlpGJqaVL5YzYDj8vwnA==
```

**Comment by carols10cents** [comment]
Yeah I have no idea either. 

I'm going to deploy master to staging now, in prep for doing a deploy to prod. I'll put staging back to this branch with the env var set when I'm done!

**Comment by kzys** [comment]
Okay. Can you add `LANG=en_US.UTF-8` on Config Vars after the staging deployment (or do you have something else on the staging)?

Ruby's strings have encodings and POSIX's locale-related environment variables affect the default encoding. It worked for me at least.

**Comment by carols10cents** [comment]
Ok, I have 9b4aaf5c deployed to staging right now, and I've set the `LANG` environment variable to `en_US.UTF-8` and `USE_FASTBOOT` to `staging-experimental`. However, I'm still seeing the same result-- when I visit https://staging.crates.io/, I only see the "This site requires JavaScript to be enabled." message.

```
$ curl --dump-header - --silent -H 'Accept: text/html' 'https://staging.crates.io/'
HTTP/2 200
content-type: text/html; charset=UTF-8
content-length: 2952
server: nginx
date: Mon, 23 Dec 2019 20:52:09 GMT
x-powered-by: Express
accept-ranges: bytes
cache-control: public, max-age=0
last-modified: Mon, 23 Dec 2019 20:01:53 GMT
etag: W/"b88-16f345a0768"
strict-transport-security: max-age=31536000
via: 1.1 vegur, 1.1 2f66aa06710fece8ed203ab0ea81eb56.cloudfront.net (CloudFront)
vary: Accept-Encoding,Accept,Accept-Encoding,Cookie
x-cache: Miss from cloudfront
x-amz-cf-pop: IAD89-C3
x-amz-cf-id: qkcJuIOGIIf1XEUBtdpItKlIprH_RGkx3DasBqKfJXLb9B1yUyphcg==
```

**Comment by kzys** [comment]
Here is mine: https://fathomless-island-39956.herokuapp.com/

I think @jtgeibel might have a working environment as well.

**Comment by carols10cents** [comment]
@jtgeibel when you get a chance, since you have access to staging now, could you compare your setup and staging's and see if I missed any environment variables or anything?

**Comment by jtgeibel** [comment]
@carols10cents I've pushed this PR to my environment, and added you to the app on Heroku.  Are things working for you at https://jtgeibel-staging-crates-io.herokuapp.com/ ?  I've done some fastboot testing in this environment before, but don't think I've tried this particular PR yet.  It seems to be working fine for me.

I'm pushing this back to staging now as well, to see if I can replicate the issue you were seeing there.

**Comment by jtgeibel** [comment]
I've added Papertrail to staging and have been looking at the logs.  It looks like in the staging environment, the request is coming with a path of `/index.html` instead of `/`, even when using curl.  Is CloudFront or something else possibly rewriting this before it gets to the app?

**Comment by kzys** [comment]
@jtgeibel Interesting. It may be. https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/DefaultRootObject.html

**Comment by pietroalbini** [comment]
@ksys I don't think so for the webapp. [Removed the root object on staging](https://github.com/rust-lang/simpleinfra/commit/e5223b4c49e608a0e8c2b5953e65b27ad2cc4275) (without touching prod), the change should propagate in around 15 minutes.

**Comment by carols10cents** [comment]
It's working!!! Thank you all for helping to figure this out!!

I also tested unsetting USE_FASTBOOT and everything works fine, so I think the cloudfront root object change is safe to make on prod, and this is safe to merge.

@bors r+

**Pull request merged**
