### PR TITLE
Support CircleCI badges

### LINKED ISSUE #800: Support badges from CircleCI
https://circleci.com

### PR DESCRIPTION
**Pull request by sfackler**
Closes #800 

ember-cli seems unhappy with Node 8 that Arch Linux has, so I haven't run frontend tests unfortunately :(

Badge docs: https://circleci.com/docs/1.0/status-badges/

### CODE REVIEW

**Comment by sfackler** [comment]
Ping @carols10cents

**Comment by locks** [comment]
cc @Turbo87 on node 8 + CLI

**Comment by Turbo87** [comment]
https://github.com/creationix/nvm

**Comment by sfackler** [comment]
Rebased

**Comment by sfackler** [comment]
The test failure looks unrelated to this PR.

**Comment by carols10cents** [comment]
Thank you for your patience on this! Rebased and force pushed to resolve a merge conflict and get tests to run again.

The code looks good, but I noticed that the CircleCi docs say this:

> (You can also link to the image without providing a circle-token, in which case the image will only appear for people who are currently logged-in to circleci.com!)

That seems unfortunate. Do you think we should optionally accept a circle-token, so at least crate authors have the ability to make their image show up for everyone?

**Comment by carols10cents** [comment]
Oooooh, one other thing:

> One small wrinkle: if your branch name includes characters that are “special” in URLs (most commonly ‘/’) they’ll need to be URL encoded when constructing status badge URLs. For example, the badge for a branch called ‘feature/nonexistent’ would be at ‘…/tree/feature%2Fnonexistent.png’.

I just tested this out by making a branch named "cratesio/test" and specifying that:

```
[badges]
circle-ci = { repository = "carols10cents/sassers", branch = "cratesio/test" }
```

and indeed, we're not URL encoding the slash; the HTML getting generated for the image is:

```
<img src="https://circleci.com/gh/carols10cents/sassers/tree/cratesio/test.svg?style=shield" alt="Circle CI build status for the cratesio/test branch" title="Circle CI build status for the cratesio/test branch">
```

and indeed the image doesn't load :-/

**Comment by sfackler** [comment]
I think the circle token comment only applies to private repos - I was worried about this as well initially. For example, [this badge](https://circleci.com/gh/sfackler/cargo-sls-distribution.svg?style=shield) page is visible to me when logged out from circle - is it visible for you as well?

Fixed up the URL encoding!

**Comment by Turbo87** [comment]
@carols10cents I'm wondering why we don't just use http://shields.io/ instead for all the badges?

**Comment by carols10cents** [comment]
> @carols10cents I'm wondering why we don't just use http://shields.io instead for all the badges?

@Turbo87 does it support everything we want? i don't see gitlab CI on there, for example

**Comment by Turbo87** [comment]
yeah, seems like GitLab is missing 😞

**Comment by sfackler** [comment]
I've also noticed shields's Cargo version badge being really slow to load.

**Comment by carols10cents** [comment]
Thanks! Sorry for taking so long on this, but I'll be deploying it once travis passes! 🍏

**Comment by sfackler** [comment]
Sweet, thanks! There's no list of badges in Cargo I need to update as well, is there?

**Comment by carols10cents** [comment]
Yeah there is: https://github.com/rust-lang/cargo/blame/1ee4edba1fa1a1d323be97bfec280764407d89e5/src/doc/manifest.md#L157

I got distracted yesterday and didn't finish deploying, but the deploy is going now!

**Pull request merged**
