### PR TITLE
categories: add parser and interpreter

### PR DESCRIPTION
**Pull request by Keruspe**

### CODE REVIEW

**Comment by carols10cents** [comment]
What are some examples of crates that would go in this category, please?

**Comment by carols10cents** [comment]
Also, what distinguishes the "Parser" category from the "Parsing" category?

**Comment by Keruspe** [comment]
Not sure interpreter would fit that much crates after thinking back about it.

The description of the parsing category indicate that it's there for libraries that help you write parsers and that concrete parsers should go in other categories. The "parser" category would be for libraries implementing a parser to be used in come software.

**Comment by carols10cents** [comment]
Ok! I've taken out interpreter then, and I tweaked parser to be "parser implementations" instead and expanded the description to hopefully distinguish clearly from parsing. Thanks!! 🌻

**Pull request merged**
