### PR TITLE
Forbid wildcard dependency constraints

### PR DESCRIPTION
**Pull request by sfackler**
This shouldn't be deployed until December 11th, but I'm opening it now so we don't forget.

### CODE REVIEW

**Comment by huonw** [comment]
Maybe this could include a link to http://doc.crates.io/faq.html#can-libraries-use--as-a-version-for-their-dependencies ?

**Comment by sfackler** [comment]
Updated

**Comment by alexcrichton** [comment]
lgtm, r+ modulo a month passing

**Comment by sfackler** [comment]
Update: we're pushing this back to January 22nd since the Cargo warning didn't make it into stable until 1.5.

**Comment by sfackler** [comment]
@alexcrichton Time to merge!

**Comment by alexcrichton** [comment]
Indeed!

**Pull request merged**
