### PR TITLE
Always count version downloads on the UTC date

### PR DESCRIPTION
**Pull request by carols10cents**
So recently I noticed that the `krate::download` test would fail for me if I was running them while I was in a different day than UTC was (that is, after 8pm EDT). This test never fails on travis because travis' machines have their system clocks in UTC.

Being in PDT last week gave me 3 extra hours where I could easily test this :) I discovered that what was happening was the version download made by [the request to the `/download` route in the test](https://github.com/rust-lang/crates.io/blob/master/src/tests/krate.rs#L977-L986) was being recorded as happening in the date in my current timezone, but the queries were asking for dates [based on yesterday in UTC](https://github.com/rust-lang/crates.io/blob/master/src/tests/krate.rs#L1011) (which was today in my current timezone!)

This changes the default value of the date column in the version_downloads table so that it's always using the current date in UTC.

This might cause some weirdness in the download graphs for a crate by day when we deploy it since it'll abruptly change how we're recording things, but oh well. I would argue the old way is incorrect and now we're fixing it :)

Also obligatory:

khan timezones meme

### CODE REVIEW

**Comment by sgrif** [comment]
What do you think about setting the connection's time zone to UTC upon connection instead?

**Comment by carols10cents** [comment]
How do I do that?

**Comment by sgrif** [comment]
`SET TIME ZONE 'UTC'`

**Comment by carols10cents** [comment]
Made you a bug! https://github.com/diesel-rs/diesel/issues/1024 ❤️ ⏲

**Comment by carols10cents** [comment]
Is this what you meant @sgrif ?

**Comment by sgrif** [comment]
Yeah, this works. We could also set [the connection customizer in R2D2](https://docs.rs/r2d2/0.7.3/r2d2/config/struct.Builder.html#method.connection_customizer)

**Comment by carols10cents** [comment]
Since https://github.com/diesel-rs/diesel/pull/1027 made it in diesel 0.15.0, I'm going to close this. Turned my system clock ahead and the test passes!!!

**Pull request closed without merging**
