### PR TITLE
 Minor Performance Enhancements and Fixes for Website 💻

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Hi, this pull request contains minor performance improvements and fixes for the website.

1) Making the Open Graph image a full path URL (`/assets/og-image.png` to `https://crates.io/assets/og-image.png`). This change ensures that the Open Graph image works as expected, as Open Graph only supports absolute file paths.

2) Adding the `inputmode` attribute to the search input for better accessibility (Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode#search).

3) Adding the `decoding` attribute to images with async for better image rendering. This is a default option in the popular Next.js framework (Reference: https://nextjs.org/docs/app/api-reference/components/image#other-props).

4) Adding `<link rel="preload" as="script" href="..." />` for faster loading of JavaScript needed for the website (Reference: https://web.dev/articles/preload-critical-assets#preloading_javascript_files).

5) Adding `scroll-behavior: smooth` in CSS for a sleeker user experience.

Extremely sorry, if I made any mistakes :)

### CODE REVIEW

**Comment by Turbo87** [comment]
Hi Sanjaiyan, first of all thanks for the PR!

Could you split the commit up so that each change has a dedicated commit? This will make it easier to:

- review and discuss the changes individually
- potentially revert a change
- find potential issues afterwards with `git bisect`

I'd personally even make it multiple PRs, but that's up to you since the changes are quite short.

**Comment by sanjaiyan-dev** [comment]
> I'd personally even make it multiple PRs, but that's up to you since the changes are quite short.

Hi @Turbo87, should I create 5 pull requests ?

**Comment by sanjaiyan-dev** [comment]
> > I'd personally even make it multiple PRs, but that's up to you since the changes are quite short.
> 
> Hi @Turbo87, should I create 5 pull requests ?

Or do I need to classify each pull request, creating one for CSS and HTML, and another for performance? Sorry for disturbing you. _(@Turbo87)_

**Comment by sanjaiyan-dev** [comment]
> Hi Sanjaiyan, first of all thanks for the PR!
> 
> Could you split the commit up so that each change has a dedicated commit? This will make it easier to:
> 
> * review and discuss the changes individually
> * potentially revert a change
> * find potential issues afterwards with `git bisect`
> 
> I'd personally even make it multiple PRs, but that's up to you since the changes are quite short.

Hi @Turbo87,

I have separated each PR according to your suggestion:

User experience-related: https://github.com/rust-lang/crates.io/pull/7801
Web load performance-related: https://github.com/rust-lang/crates.io/pull/7800
Social media SEO optimization-related: https://github.com/rust-lang/crates.io/pull/7802"

**Pull request closed without merging**
