### PR TITLE
Upgrade dependencies and Ember to 2.13

### PR DESCRIPTION
**Pull request by bjornharrtell**
### Before
```
File sizes:
 - dist/assets/cargo-502d5135cd3fcd2b77d64b2027927750.js: 183.81 KB (22.55 KB gzipped)
 - dist/assets/cargo-ff8d7f4b30c09a6d7164b5b110300d4e.css: 19.43 KB (4.11 KB gzipped)
 - dist/assets/vendor-45cafdb0402c3bdc8ab00ba98c34b467.js: 1.14 MB (285.66 KB gzipped)
 - dist/assets/vendor-924cc62bda01ca298267563aa0a649b0.css: 2.11 KB (969 B gzipped)
```
### After
``` 
File sizes:
 - dist/assets/cargo-2f40149c023ece6c841fe2262c0b87c1.js: 155.18 KB (21.44 KB gzipped)
 - dist/assets/cargo-ff8d7f4b30c09a6d7164b5b110300d4e.css: 19.43 KB (4.11 KB gzipped)
 - dist/assets/vendor-378639b713e879bbf548e26dfed52167.js: 1.19 MB (292.47 KB gzipped)
 - dist/assets/vendor-cbfb16fd993fc7bc10c973ed8ad19ca2.css: 2.02 KB (934 B gzipped)
```

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Ready for review :) Ping @carols10cents and @alexcrichton.

**Comment by carols10cents** [comment]
@bjornharrtell thanks!! I'm sorry I've let this sit so long, I'll try and take a look at this soon, hopefully in the next few days.

It looks like travis is failing though, could you also take a look at that? I'm seeing:

- [A deprecation warning](https://travis-ci.org/rust-lang/crates.io/jobs/236087755#L1135): `DEPRECATION: Ember.MODEL_FACTORY_INJECTIONS is no longer required [deprecation id: ember-metal.model_factory_injections] See http://emberjs.com/deprecations/v2.x#toc_code-ember-model-factory-injections for more details.`
- [A search test failing](https://travis-ci.org/rust-lang/crates.io/jobs/236087755#L1177) with [`undefined is not a function`](https://travis-ci.org/rust-lang/crates.io/jobs/236087755#L1208)

Thanks!

**Comment by bjornharrtell** [comment]
Will take a look but away until next week.

**Comment by carols10cents** [comment]
No problem!

**Comment by carols10cents** [comment]
Replaced by #760!

**Pull request closed without merging**
