### PR TITLE
Remove "Authors" section from crate details page

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/rust-lang/rfcs/pull/3052 😉 

r? @pietroalbini

### CODE REVIEW

**Comment by pietroalbini** [comment]
The RFC has been merged!

**Comment by Turbo87** [comment]
yep, saw it and just rebased the PR :)

**Comment by pietroalbini** [comment]
Thanks :heart: 

I'd prefer for a frontend person to review this though :)

**Review by hi-rustin — APPROVED** [review]
LGTM

**Pull request merged**
