### PR TITLE
Add a simple link to display reverse dependencies

### PR DESCRIPTION
**Pull request by winding-lines**
This is related to issue #99, it is the simplest approach I can think of. I can add more functionality if desired, for example display the link only if there are reverse dependencies.

Let me know what you think.

### CODE REVIEW

**Comment by alexcrichton** [comment]
This may want a bit of visual separation to set it a apart from the rest of the links:



cc @wycats, thoughts on the look-and-feel of this link?

**Comment by winding-lines** [comment]
@alexcrichton here is the output using one of the existing css classes (small) and with the count of reverse dependencies.
screen shot 2015-01-03 at 9 32 39 am

A different option for the UI is to add inline the first 3 (x) reverse dependencies and then add an optional link to the rest.

**Comment by alexcrichton** [comment]
Interesting! I'd probably put the numbers in parens, and I guess we probably don't want to show the link if no reverse dependencies exist.

My first thought was to not show the names of reverse dependencies, but perhaps there's precedent for it?

**Comment by wycats** [comment]
I'll reply to this in more detail tomorrow. I definitely want something like this, but not QUITE this.

**Comment by winding-lines** [comment]
@wycats, thx for your input :)

BTW, this is Marius, we met in Dec in Mountain View @ Linkedin.

**Comment by huonw** [comment]
@wycats ping

**Comment by amutake** [comment]
Just for your information, I wrote a simple chrome extension to see reverse dependencies.
https://github.com/amutake/crates.io-reverse-dependencies

**Comment by wycats** [comment]
@amutake would be cool to get something like this in, but a fourth column is too narrow imo.

Maybe right below the three columns in full-width with the name "Dependents" instead of "Reverse-Dependencies"?

**Pull request closed without merging**
