### PR TITLE
Move from npm cli -> yarn

### PR DESCRIPTION
**Pull request by steveklabnik**
yarn is a new cli for the npm registry from Facebook, Google, and Tilde.
It's patterned after Cargo, and @wycats was involved in making it. The
big things we care about here:
1. It is faster. 30s vs 45 for npm cli on my mcahine.
2. It has a lockfile. Cargo has a lockfile. Lockfiles are good.

This commit adds a yarn.lock, and fixes our .travis.yml to use yarn
instead.

### CODE REVIEW

**Comment by rwjblue** [comment]
Should likely change:

```yml
 cache:
   directories:
     - node_modules
```

To:

```yml
 cache:
   directories:
     - $HOME/.yarn-cache
```

Yarn symlinks from `~/.yarn-cache` into `node_modules` (using as flat a structure as is possible), so caching that instead of `node_modules` (which is basically just symlinks AFAICT?) seems better  and likely faster.

**Comment by steveklabnik** [comment]
@rwjblue Ah thanks! I wasn't aware. :+1:

**Comment by steveklabnik** [comment]
Interesting, Travis seems to be failing because I have a newer node locally. Might as well fix that too; I was planning on doing it, but in a different PR.

**Comment by rwjblue** [comment]
Also, `yarn` does not support Node 0.12, so you will need to update to at least 4.0 (I'd say 6.0 is probably better since it will be next LTS).  I'm looking in the Travis docs for what the syntax is for that (since the declared language is `rust`)

**Comment by steveklabnik** [comment]
@rwjblue just pushed a new commit with that :smile:

**Comment by steveklabnik** [comment]
I had asked @alexcrichton what it would take to upgrade node, given that we're using a buildpack, https://github.com/tonycoco/heroku-buildpack-ember-cli/blob/master/bin/compile#L36-L37 should Just Do It.

**Comment by steveklabnik** [comment]
Hm, checking why this failed this time, and didn't last time...

**Comment by steveklabnik** [comment]
... i reorganized these commits so that the node upgrade happens first, but github seems to still show them out of order. It looks like travis is testing the second commit, which is accurate, though?

Anyway, I am 99% sure this will pass, and so is now ready for review.

**Comment by steveklabnik** [comment]
I have no idea what Travis's beef is here, this runs just fine locally for me. gah.

**Comment by rjgoldsborough** [comment]
Seems to maybe be a side effect of https://github.com/yarnpkg/yarn/issues/733 perhaps.

@steveklabnik, I sent you a PR to add an ember script, which I think might fix it.

**Comment by steveklabnik** [comment]
Oh interesting. I just switched travis to call `ember test` rather than going through `npm run test`, but that might be better. Lemme check it out.

**Comment by steveklabnik** [comment]
@rjgoldsborough looks like that didn't work.

**Comment by rjgoldsborough** [comment]
Ah darn. Sounds like calling ember directly is the best fix for now.

**Comment by steveklabnik** [comment]
Okay! @carols10cents @alexcrichton what do you think?

**Comment by rjgoldsborough** [comment]
I do wonder if that'll pop up when trying to run too.

But it doesn't happen locally so it's hard to tell.

**Comment by carols10cents** [comment]
So I pulled down this branch locally and followed the instructions in the readme. Specifically, I ran:

```
npm install -g yarn
yarn
yarn run bower install
```

Those seemed to work fine, then I did this: 

```
 $ yarn run start:staging
yarn run v0.15.1
$ "yarn run ember server --proxy https://staging-crates-io.herokuapp.com"
sh: yarn run ember server --proxy https://staging-crates-io.herokuapp.com: No such file or directory
error Command failed with exit code 127.
info Visit http://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Am I doing something wrong? Is it the same issue yinz linked to?

**Comment by steveklabnik** [comment]
Ugh, okay. So yeah, something is the matter with npm scripts here. I think it's the issue we linked to. We'll have to wait for that to get cleared up, I think.

**Comment by rjgoldsborough** [comment]
Yeah I think that's still the issue.

I know with npm run you used to have to separate the command and arguments with --.
https://docs.npmjs.com/cli/run-script

Maybe try changing the `start:staging` command to run `yarn run ember -- server --proxy https://staging-crates-io.herokuapp.com`

I tried it both ways locally and got different results I think
```
yarn run v0.15.1
$ yarn run ember server --proxy https://staging-crates-io.herokuapp.com
yarn run v0.15.1
$ /Users/ducks/devel/rust/crates.io/node_modules/.bin/ember server
```

vs
```
yarn run v0.15.1
$ yarn run ember -- server --proxy https://staging-crates-io.herokuapp.com
yarn run v0.15.1
$ /Users/ducks/devel/rust/crates.io/node_modules/.bin/ember server --proxy https://staging-crates-io.herokuapp.com
```

**Comment by steveklabnik** [comment]
Filed https://github.com/yarnpkg/yarn/issues/780 just to make sure.

**Comment by steveklabnik** [comment]
Looks like a possible fix for @carols10cents may have landed this morning https://github.com/yarnpkg/yarn/pull/809

**Comment by steveklabnik** [comment]
Oh also, supposedly this replaces Bower as well. I still have `bower install` here, so I should figure that out...

**Comment by rjgoldsborough** [comment]
It looks like there are a few known issues with that too for now

https://github.com/yarnpkg/yarn/issues/616
https://github.com/yarnpkg/yarn/issues/864

**Comment by steveklabnik** [comment]
@rjgoldsborough was just about to say the same https://github.com/yarnpkg/yarn/pull/896, probably best to hold off. cool.

**Comment by alexcrichton** [comment]
@steveklabnik is this ready to go? Or perhaps still waiting for a yarn point release?

**Comment by steveklabnik** [comment]
I believe that it was released, let me kick off another Travis build to check.

**Comment by steveklabnik** [comment]
Looks like travis is green now 🎊 

I would like to double check that the issues @carols10cents had are fixed; I can run those commands tomorrow, but I _think_ they should Just Work now.

**Comment by carols10cents** [comment]
I updated yarn to v0.16.1 and I was able to run the setup steps, run just the frontend proxying to staging, run both kinds of tests, and run the backend locally and the front end pointing to that! 🎉 🎊 

One nit though: Line 32 in the README still says "npm start".

**Comment by alexcrichton** [comment]
@steveklabnik I remember talking about this but I forget the resolution, do you know if this'll work on heroku deployments as well? Do we need to switch buildpacks to a yarn-enabled buildpack?

**Comment by steveklabnik** [comment]
@alexcrichton ah, so we talked about it for the node upgrade; that def. works with the existing buildpack. That is, the buildpack looks at [this line](https://github.com/rust-lang/crates.io/pull/457/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R19) to install a node version. But it still uses npm for actually building.

In theory, it would still be fine to just ship this; this doesn't _break_ npm from working. And then we could work out the buildpack issues. But, the more conservative choice is to hold off until that's good to go as well. I've opened https://github.com/tonycoco/heroku-buildpack-ember-cli/issues/139 to see what the buildpack's maintainers think about adding support.

**Comment by steveklabnik** [comment]
So, given that the buildpack author has not replied, how should I proceed? Should I just fork and add it and we can use my fork?

**Comment by alexcrichton** [comment]
Well that's only mildly disturbing... @samphippen out of curiosity are you familiar if there's a "best practice" for deploying ember to Heroku? If so, is it still the buildpack at https://github.com/tonycoco/heroku-buildpack-ember-cli?

**Comment by samphippen** [comment]
Honestly, I'd support forking and running off a version that supports yarn. Buildpacks are the sort of thing that you're not likely to change often going forward. Also: having production usage would be a good reason for the original authors to merge. 🚀

**Comment by alexcrichton** [comment]
Ok, thanks! @steveklabnik if you'd like to fork I'd be cool merging!

**Comment by steveklabnik** [comment]
I'll try to get to it soon!

**Comment by steveklabnik** [comment]
Sooooooooooooooooooooooooo six days ago https://github.com/tonycoco/heroku-buildpack-ember-cli/commit/01f2e3542057e407bc809bba04e8303ba80f9412

But the "official" one is still experimental. So. I don't even know.

**Comment by alexcrichton** [comment]
Eh if it's the same code it's what we've been using all along, so that should be fine.

**Comment by steveklabnik** [comment]
@ryanponce wants to take a shot at this, so I'm gonna work with them on it

**Comment by steveklabnik** [comment]
Relevant to our interests https://github.com/heroku/heroku-buildpack-nodejs/issues/337#issuecomment-253286196

**Comment by alexcrichton** [comment]
Awesome! @steveklabnik want to include that here and I'll test it out in staging?

**Comment by steveklabnik** [comment]
Yeah, gonna take a look at it soon. @ryanponce did you get a chance to play with any of this the other day?

**Comment by ryanponce** [comment]
@steveklabnik Ah not yet. You guys go for it, I'll pick up another one.

**Comment by rjgoldsborough** [comment]
I'd love to help finish the move to yarn so just holler if you don't wanna bother with it. :)

I'll admit I don't know a whole lot about heroku but looks like this might be added with the`buildpacks:add`command?

**Comment by alexcrichton** [comment]
I believe the only change necessary is to `.buildpacks` in this repo, and that'll propagate naturally

**Comment by rjgoldsborough** [comment]
Cool. I sent @steveklabnik a PR that adds that.

Thanks.

**Comment by steveklabnik** [comment]
I have since merged the PR, let's give it a try!

**Comment by alexcrichton** [comment]
Deployed!

**Pull request merged**
