### PR TITLE
frontend: show descriptions in category list

### PR DESCRIPTION
**Pull request by ppannuto**
The manifest documentation https://doc.rust-lang.org/cargo/reference/manifest.html
suggests https://crates.io/category_slugs as a list of all categories, but this
is a fairly terse list of nouns presently. The description is useful for making
an informed decision about which categories apply.

### CODE REVIEW

**Comment by jonhoo** [comment]
This actually came up in a discussion [over here](https://www.youtube.com/watch?v=KS14JIRZTBw&lc=UgyKluwwFSslCLOOYMp4AaABAg.8iowhgV0Y6i8ip4T38NQBV) too. Could we also make `category_slugs` easier to find? I've wanted that page *so* many times, and never new it existed until it was pointed out to me very recently. Perhaps we could also show the slugs in the regular category listing? Or at least add a link on the category page to the list of slugs?

**Comment by carols10cents** [comment]
We actually just added a link to the category slugs page in the Docs menu for https://github.com/rust-lang/crates.io/issues/721; I'll have that deployed in a bit. I'd also accept another pull request adding a link to the slugs page from the category page :)

**Comment by carols10cents** [comment]
So it turns out the API response for category slugs didn't include the category description, so I added that. It also needed to be added to the ember model. Then I added some backend and frontend tests so that we don't break this in the future 🤞 I just went ahead and took care of this, please take a look at my changes; if you work on another PR, I'd be happy to help you try out your changes and add tests!

bors: r+

**Comment by ppannuto** [comment]
Brilliant, thank you. Sorry this was a little incomplete to start off with..

**Comment by carols10cents** [comment]
No worries! :)

**Pull request merged**
