### PR TITLE
Show which dependencies are optional on the crate page

### LINKED ISSUE #233: Show which dependencies are optional
Show which dependencies are optional, so that it's easier to judge what a package depends on in its default configuration.

### PR DESCRIPTION
**Pull request by bluss**
Same idea & style as the yanked marker (but not red).

Fixes #233

### CODE REVIEW

**Comment by bluss** [comment]
I'm failing to install & run ember, I have no idea how any of this works. So this is so far entirely untested!

**Comment by alexcrichton** [comment]
Hm looks like some extra css may be needed to get it to align right?



I like the idea though!

**Comment by bluss** [comment]
Thanks for taking a look at it! It seems to me the text needs to be inside the `<li>` generated by `{{link-to-dep dep=dep}}`

**Comment by alexcrichton** [comment]
Looks good to me!

**Comment by bluss** [comment]
Yay!

**Pull request merged**
