### PR TITLE
Optimize reverse dependencies query

### PR DESCRIPTION
**Pull request by paolobarbolini**
This optimizes the reverse dependencies query by saving the output of `to_semver_no_prerelease(num)` into a `GENERATED` column and adding indexes. On an Hetzer CAX21 server querying reverse dependencies for `serde` now takes 600ms.

<details>
<summary>Initial attempt at optimizing the query</summary>

This optimizes the reverse dependencies query by using [Common Table Expression (CTE) Materialization](https://www.postgresql.org/docs/current/queries-with.html#id-1.5.6.12.7) as a method of steering the query optimizer into the desired direction.

This makes http://localhost:8888/api/v1/crates/serde/reverse_dependencies?page=1&per_page=10 respond in 3 seconds, which is much nicer than having it reach the 10 seconds timeout as it did before.

---

While trying to make the query faster on PG 16beta2 I also created two indexes but they don't seem to be helping here so I left them out of migrations for now.
I'll save them here for later:

```sql
CREATE INDEX idx1 ON versions (id, crate_id);
CREATE INDEX idx2 ON versions (crate_id, to_semver_no_prerelease(num) DESC NULLS LAST, id) WHERE NOT yanked;
```

```sql
WITH crate_versions_crate_ids AS MATERIALIZED (
    SELECT versions.crate_id
    FROM versions
    INNER JOIN dependencies
      ON dependencies.version_id = versions.id
    WHERE dependencies.crate_id = $1
    GROUP BY versions.crate_id
), all_versions AS MATERIALIZED (
    SELECT
        id,
        crate_id
    FROM (
        SELECT
            versions.id,
            versions.crate_id,
            row_number() OVER (
                PARTITION BY crate_id
                ORDER BY to_semver_no_prerelease(num) DESC NULLS LAST
            ) rn
        FROM versions
        WHERE NOT versions.yanked
        -- This is completely redundant, but it's faster to filter the versions
        -- early even if this subselect is done via an index scan.
        AND versions.crate_id IN (
            SELECT crate_id
            FROM crate_versions_crate_ids
        )
    ) v
    WHERE rn = 1
)

-- Apply pagination to the whole thing
SELECT *, COUNT(*) OVER () as total FROM (
    -- Multple dependencies can exist, make it distinct
    SELECT DISTINCT ON (crate_downloads, crate_name)
    dependencies.*,
    crates.downloads AS crate_downloads,
    crates.name AS crate_name
    FROM dependencies
    -- We only want the crates whose *max* version is dependent, so we join on a
    -- subselect that includes the versions with their ordinal position
    INNER JOIN all_versions AS versions
      ON versions.id = dependencies.version_id
    INNER JOIN crates
      ON crates.id = versions.crate_id
    WHERE dependencies.crate_id = $1
    ORDER BY crate_downloads DESC
) t
OFFSET $2
LIMIT $3
```
</details>

### CODE REVIEW

**Comment by Turbo87** [comment]
how long did it take to add the indexes? the thing to keep in mind with these operations is that our database migrations currently are running in between the old server process stopping and the new ones starting, in other words: they can cause downtime if they take a long time to run.

**Comment by LawnGnome** [comment]
> how long did it take to add the indexes?

Locally, 3.4 seconds, but I obviously have no way of extrapolating that into our production environment.

**Comment by paolobarbolini** [comment]
They should be very fast to generate, since the `versions` table isn't even 1 million rows.
I'll add migrations for the indexes later once I get a chance to re-explore `diesel`.

Yesterday I wanted to do a few more benchmarks and see how long each step took but `EXPLAIN ANALYZE` gave me some issues https://t.me/pg_sql/78414

**Comment by paolobarbolini** [comment]
In a drastic turn of events I was able to further optimize my query to almost half the execution time and no materialize CTEs. I'll see if there are any indexes which can make it even faster.

<details>
<summary>I've saved the previous query here.</summary>

```sql
WITH crate_versions_crate_ids AS MATERIALIZED (
    SELECT versions.crate_id
    FROM versions
    INNER JOIN dependencies
      ON dependencies.version_id = versions.id
    WHERE dependencies.crate_id = $1
    GROUP BY versions.crate_id
), all_versions AS MATERIALIZED (
    SELECT
        id,
        crate_id
    FROM (
        SELECT
            versions.id,
            versions.crate_id,
            row_number() OVER (
                PARTITION BY crate_id
                ORDER BY to_semver_no_prerelease(num) DESC NULLS LAST
            ) rn
        FROM versions
        WHERE NOT versions.yanked
        -- This is completely redundant, but it's faster to filter the versions
        -- early even if this subselect is done via an index scan.
        AND versions.crate_id IN (
            SELECT crate_id
            FROM crate_versions_crate_ids
        )
    ) v
    WHERE rn = 1
)

-- Apply pagination to the whole thing
SELECT *, COUNT(*) OVER () as total FROM (
    -- Multple dependencies can exist, make it distinct
    SELECT DISTINCT ON (crate_downloads, crate_name)
    dependencies.*,
    crates.downloads AS crate_downloads,
    crates.name AS crate_name
    FROM dependencies
    -- We only want the crates whose *max* version is dependent, so we join on a
    -- subselect that includes the versions with their ordinal position
    INNER JOIN all_versions AS versions
      ON versions.id = dependencies.version_id
    INNER JOIN crates
      ON crates.id = versions.crate_id
    WHERE dependencies.crate_id = $1
    ORDER BY crate_downloads DESC
) t
OFFSET $2
LIMIT $3
```
</details>

**Comment by paolobarbolini** [comment]
I still haven't looked into how to make diesel happy with my new column, but I've improved the query even more and I've done some benchmarks.

All tests done on the serde crate using an Hetzner CAX21 machine with PostgreSQL 14 installed natively on Debian 12.

## Current query

Execution time: 3.7s

<details><summary>EXPLAIN ANALYZE output</summary>

```
                                                                                                                             QUERY PLAN                                                                                                                             
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=702583.57..702583.87 rows=10 width=105) (actual time=3891.104..3891.120 rows=10 loops=1)
   ->  WindowAgg  (cost=702583.57..702627.10 rows=1451 width=105) (actual time=3544.665..3544.680 rows=10 loops=1)
         ->  Unique  (cost=702583.57..702594.45 rows=1451 width=97) (actual time=3524.246..3536.709 rows=29142 loops=1)
               ->  Sort  (cost=702583.57..702587.20 rows=1451 width=97) (actual time=3524.243..3530.146 rows=29876 loops=1)
                     Sort Key: crates.downloads DESC, crates.name
                     Sort Method: external merge  Disk: 2552kB
                     ->  Nested Loop  (cost=421760.41..702507.37 rows=1451 width=97) (actual time=2588.079..3484.822 rows=29876 loops=1)
                           ->  Nested Loop  (cost=421759.99..696235.03 rows=1451 width=85) (actual time=2588.019..3352.955 rows=29876 loops=1)
                                 ->  Subquery Scan on versions  (cost=421759.56..653347.43 rows=4063 width=8) (actual time=2587.984..3067.224 rows=30142 loops=1)
                                       Filter: (versions.rn = 1)
                                       Rows Removed by Filter: 299720
                                       ->  WindowAgg  (cost=421759.56..643190.06 rows=812589 width=529) (actual time=2587.980..3050.082 rows=329862 loops=1)
                                             ->  Sort  (cost=421759.56..423791.03 rows=812589 width=40) (actual time=2587.935..2925.225 rows=329862 loops=1)
                                                   Sort Key: versions_1.crate_id, (to_semver_no_prerelease((versions_1.num)::text)) DESC NULLS LAST, versions_1.id DESC
                                                   Sort Method: external merge  Disk: 15880kB
                                                   ->  Hash Join  (cost=68866.51..319773.65 rows=812589 width=40) (actual time=605.726..2177.869 rows=329862 loops=1)
                                                         Hash Cond: (versions_1.crate_id = versions_2.crate_id)
                                                         ->  Seq Scan on versions versions_1  (cost=0.00..36586.79 rows=812589 width=14) (actual time=0.035..164.210 rows=810325 loops=1)
                                                               Filter: (NOT yanked)
                                                               Rows Removed by Filter: 49254
                                                         ->  Hash  (cost=68355.86..68355.86 rows=40852 width=4) (actual time=605.344..605.347 rows=31030 loops=1)
                                                               Buckets: 65536  Batches: 1  Memory Usage: 1603kB
                                                               ->  HashAggregate  (cost=67947.34..68355.86 rows=40852 width=4) (actual time=594.153..600.082 rows=31030 loops=1)
                                                                     Group Key: versions_2.crate_id
                                                                     Batches: 1  Memory Usage: 3089kB
                                                                     ->  Hash Join  (cost=50689.96..67221.66 rows=290271 width=4) (actual time=265.028..525.237 rows=298730 loops=1)
                                                                           Hash Cond: (dependencies_1.version_id = versions_2.id)
                                                                           ->  Index Only Scan using dependencies_crate_id_version_id_idx on dependencies dependencies_1  (cost=0.43..10144.18 rows=290271 width=4) (actual time=0.045..40.243 rows=298730 loops=1)
                                                                                 Index Cond: (crate_id = 463)
                                                                                 Heap Fetches: 0
                                                                           ->  Hash  (cost=36586.79..36586.79 rows=859579 width=8) (actual time=264.618..264.619 rows=859579 loops=1)
                                                                                 Buckets: 131072  Batches: 16  Memory Usage: 3128kB
                                                                                 ->  Seq Scan on versions versions_2  (cost=0.00..36586.79 rows=859579 width=8) (actual time=0.012..129.343 rows=859579 loops=1)
                                 ->  Index Scan using index_dependencies_version_id on dependencies  (cost=0.43..10.54 rows=2 width=81) (actual time=0.008..0.009 rows=1 loops=30142)
                                       Index Cond: (version_id = versions.id)
                                       Filter: (crate_id = 463)
                                       Rows Removed by Filter: 10
                           ->  Index Scan using packages_pkey on crates  (cost=0.42..4.32 rows=1 width=20) (actual time=0.004..0.004 rows=1 loops=29876)
                                 Index Cond: (id = versions.crate_id)
 Planning Time: 1.761 ms
 JIT:
   Functions: 47
   Options: Inlining true, Optimization true, Expressions true, Deforming true
   Timing: Generation 6.214 ms, Inlining 10.651 ms, Optimization 191.780 ms, Emission 144.183 ms, Total 352.828 ms
```
</details>

## First optimization (3ac37711986a6d48fdae1f3042568a40f384755c)

Execution time: 2s

<details><summary>EXPLAIN ANALYZE output</summary>

```
                                                                                                                                         QUERY PLAN                                                                                         
                                                 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------
 Limit  (cost=281210.31..281210.34 rows=10 width=105) (actual time=2233.301..2243.808 rows=10 loops=1)
   ->  Sort  (cost=281210.31..281213.94 rows=1451 width=105) (actual time=2173.323..2183.829 rows=10 loops=1)
         Sort Key: crates.downloads DESC
         Sort Method: top-N heapsort  Memory: 27kB
         ->  WindowAgg  (cost=281135.43..281178.96 rows=1451 width=105) (actual time=2157.723..2175.177 rows=29142 loops=1)
               ->  Unique  (cost=281135.43..281146.31 rows=1451 width=97) (actual time=2135.886..2159.876 rows=29142 loops=1)
                     ->  Sort  (cost=281135.43..281139.05 rows=1451 width=97) (actual time=2135.884..2152.799 rows=29876 loops=1)
                           Sort Key: crates.downloads, crates.name
                           Sort Method: external merge  Disk: 2552kB
                           ->  Nested Loop  (cost=203459.52..281059.23 rows=1451 width=97) (actual time=1162.672..2106.292 rows=29876 loops=1)
                                 ->  Nested Loop  (cost=203459.10..274786.89 rows=1451 width=85) (actual time=1162.614..1974.642 rows=29876 loops=1)
                                       ->  Subquery Scan on versions  (cost=203458.67..231899.29 rows=4063 width=8) (actual time=1162.576..1673.378 rows=30142 loops=1)
                                             Filter: (versions.rn = 1)
                                             Rows Removed by Filter: 299720
                                             ->  WindowAgg  (cost=203458.67..221741.92 rows=812589 width=498) (actual time=1162.571..1651.178 rows=329862 loops=1)
                                                   ->  Sort  (cost=203458.67..205490.14 rows=812589 width=41) (actual time=1162.521..1510.142 rows=329862 loops=1)
                                                         Sort Key: versions_1.crate_id, versions_1.semver_no_prerelease DESC NULLS LAST, versions_1.id DESC
                                                         Sort Method: external merge  Disk: 15880kB
                                                         ->  Hash Join  (cost=59977.20..98697.26 rows=812589 width=41) (actual time=372.078..771.047 rows=329862 loops=1)
                                                               Hash Cond: (versions_1.crate_id = versions_2.crate_id)
                                                               ->  Seq Scan on versions versions_1  (cost=0.00..36586.79 rows=812589 width=41) (actual time=2.353..178.390 rows=810325 loops=1)
                                                                     Filter: (NOT yanked)
                                                                     Rows Removed by Filter: 49254
                                                               ->  Hash  (cost=59466.55..59466.55 rows=40852 width=4) (actual time=369.334..379.831 rows=31030 loops=1)
                                                                     Buckets: 65536  Batches: 1  Memory Usage: 1603kB
                                                                     ->  Finalize HashAggregate  (cost=58649.51..59058.03 rows=40852 width=4) (actual time=358.787..374.902 rows=31030 loops=1)
                                                                           Group Key: versions_2.crate_id
                                                                           Batches: 1  Memory Usage: 3089kB
                                                                           ->  Gather  (cost=49866.33..58445.25 rows=81704 width=4) (actual time=315.934..350.448 rows=67198 loops=1)
                                                                                 Workers Planned: 2
                                                                                 Workers Launched: 2
                                                                                 ->  Partial HashAggregate  (cost=48866.33..49274.85 rows=40852 width=4) (actual time=287.572..292.390 rows=22399 loops=3)
                                                                                       Group Key: versions_2.crate_id
                                                                                       Batches: 1  Memory Usage: 2833kB
                                                                                       Worker 0:  Batches: 1  Memory Usage: 2577kB
                                                                                       Worker 1:  Batches: 1  Memory Usage: 2833kB
                                                                                       ->  Parallel Hash Join  (cost=37449.99..48563.96 rows=120946 width=4) (actual time=174.243..256.320 rows=99577 loops=3)
                                                                                             Hash Cond: (dependencies_1.version_id = versions_2.id)
                                                                                             ->  Parallel Index Only Scan using dependencies_crate_id_version_id_idx on dependencies dependencies_1  (cost=0.43..8450.93 rows=120946 width=4) (actual time=0.148..21.267 rows=99577 loops=3)
                                                                                                   Index Cond: (crate_id = 463)
                                                                                                   Heap Fetches: 0
                                                                                             ->  Parallel Hash  (cost=31572.58..31572.58 rows=358158 width=8) (actual time=128.810..128.812 rows=286526 loops=3)
                                                                                                   Buckets: 131072  Batches: 16  Memory Usage: 3168kB
                                                                                                   ->  Parallel Seq Scan on versions versions_2  (cost=0.00..31572.58 rows=358158 width=8) (actual time=6.975..71.583 rows=286526 loops=3)
                                       ->  Index Scan using index_dependencies_version_id on dependencies  (cost=0.43..10.54 rows=2 width=81) (actual time=0.008..0.010 rows=1 loops=30142)
                                             Index Cond: (version_id = versions.id)
                                             Filter: (crate_id = 463)
                                             Rows Removed by Filter: 10
                                 ->  Index Scan using packages_pkey on crates  (cost=0.42..4.32 rows=1 width=20) (actual time=0.004..0.004 rows=1 loops=29876)
                                       Index Cond: (id = versions.crate_id)
 Planning Time: 0.828 ms
 JIT:
   Functions: 82
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 4.821 ms, Inlining 0.000 ms, Optimization 3.426 ms, Emission 75.976 ms, Total 84.222 ms
```
</details>

## Second optimization (3c047baf73829339c0855a352a4790ca5a67779b)

Execution time: 600ms

<details><summary>EXPLAIN ANALYZE output</summary>

```
                                                                                                              QUERY PLAN                                                                                                               
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=155691.23..155691.26 rows=10 width=105) (actual time=669.105..669.220 rows=10 loops=1)
   ->  Sort  (cost=155691.23..155847.18 rows=62380 width=105) (actual time=654.772..654.886 rows=10 loops=1)
         Sort Key: crates.downloads DESC
         Sort Method: top-N heapsort  Memory: 27kB
         ->  WindowAgg  (cost=145362.59..154343.22 rows=62380 width=105) (actual time=639.322..646.224 rows=29142 loops=1)
               ->  Unique  (cost=145362.59..152939.67 rows=62380 width=97) (actual time=613.833..631.179 rows=29142 loops=1)
                     ->  Gather Merge  (cost=145362.59..152627.77 rows=62380 width=97) (actual time=613.832..625.586 rows=29876 loops=1)
                           Workers Planned: 2
                           Workers Launched: 2
                           ->  Sort  (cost=144362.57..144427.55 rows=25992 width=97) (actual time=583.897..585.314 rows=9959 loops=3)
                                 Sort Key: crates.downloads, crates.name
                                 Sort Method: quicksort  Memory: 2227kB
                                 Worker 0:  Sort Method: quicksort  Memory: 1659kB
                                 Worker 1:  Sort Method: quicksort  Memory: 1286kB
                                 ->  Nested Loop  (cost=1.27..142456.60 rows=25992 width=97) (actual time=25.745..573.534 rows=9959 loops=3)
                                       ->  Merge Join  (cost=0.84..43084.86 rows=17022 width=20) (actual time=25.561..272.272 rows=39288 loops=3)
                                             Merge Cond: (crates.id = versions.crate_id)
                                             ->  Parallel Index Only Scan using index_crates_id_downloads_name on crates  (cost=0.42..3547.01 rows=51027 width=20) (actual time=0.068..8.119 rows=40822 loops=3)
                                                   Heap Fetches: 0
                                             ->  Unique  (cost=0.42..38729.41 rows=40852 width=490) (actual time=0.146..232.401 rows=117792 loops=3)
                                                   ->  Index Only Scan using index_versions_crate_id_semver_no_prerelease_id on versions  (cost=0.42..36697.94 rows=812589 width=490) (actual time=0.144..162.243 rows=810223 loops=3)
                                                         Heap Fetches: 0
                                       ->  Index Scan using index_dependencies_version_id on dependencies  (cost=0.43..5.82 rows=2 width=81) (actual time=0.007..0.007 rows=0 loops=117863)
                                             Index Cond: (version_id = versions.id)
                                             Filter: (crate_id = 463)
                                             Rows Removed by Filter: 5
 Planning Time: 0.374 ms
 JIT:
   Functions: 47
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 6.734 ms, Inlining 0.000 ms, Optimization 2.020 ms, Emission 46.482 ms, Total 55.236 ms
```
</details>

---

Unfortunately the second optimization doesn't seem to work on Postgres 13. For some reason the optimizer isn't able to use the index `index_versions_crate_id_semver_no_prerelease_id` at all or doesn't use it efficiently even when pushed.

**Comment by LawnGnome** [comment]
> I still haven't looked into how to make diesel happy with my new column, but I've improved the query even more and I've done some benchmarks.

I wanted to try this out locally, so I had a crack at it. I think 147366cc259a4f3021027cbee96d5aa6e635efab would finish wiring this up, if you want to cherry-pick that in. (Or I can push it to your branch, but I didn't want to do it without talking to you first.)

There's a related tweak that we also need to make to the definition of `to_semver_no_prerelease` to avoid a harmless (but annoying) error in the `schema.sql` generated in the database dump, but I'll jump over to #6966 to explain that, since we're touching that function there anyway.

### Migration downtime

One thought I had on this was that, if we change the up migrations to use `CREATE INDEX IF NOT EXISTS` and `ADD COLUMN IF NOT EXISTS`, we could actually execute them manually before deploying the new version, thereby essentially turning the migrations into no-ops when we do the actual deployment.

Obviously we'd want to test this on staging before actually doing it, but a basic smoke test locally seemed to work: the new generated column didn't interfere with crates.io operation or crate publishing.

Thoughts, @Turbo87?

**Comment by Turbo87** [comment]
> One thought I had on this was that, if we change the up migrations to use `CREATE INDEX IF NOT EXISTS` and `ADD COLUMN IF NOT EXISTS`, we could actually execute them manually before deploying the new version, thereby essentially turning the migrations into no-ops when we do the actual deployment.

yeah, that seems like a good solution. might make sense to add a comment to the migration script in that case.

**Comment by paolobarbolini** [comment]
I've added `IF NOT EXISTS` to indexes and the new column without a comment since that's how other indexes seem to have done it.

**Comment by paolobarbolini** [comment]
This should now be ready. After adding indexes it might be necessary to `VACUUM versions;` if the optimizer doesn't pick up the better query plan.

**Pull request merged**
